# UE Data Mining - Projet

Notebook à compléter dans le cadre du projet de l’UE Data Mining des Master 2 Intelligence Artificielle et Master 2 Data Science de l’année scolaire 2026-2027.

* Nom du groupe :
* Membres du groupe :
    * Prénom NOM
    * Ghilas Leticia

## Pensez à mettre des titres

Et du texte pour expliquer les différentes étapes de votre raisonnement, les résultats obtenus et les conclusions que vous en avez tiré.

Pour rappel, ce notebook sera aussi votre rapport sur ce projet, donc soyez précis et rigoureux dans ce que vous décrivez et écrivez.

In [91]:
# TODO
!git clone https://github.com/Sheik-info/20262027-UE-DataMining-Project.git
%cd 20262027-UE-DataMining-Project

fatal: destination path '20262027-UE-DataMining-Project' already exists and is not an empty directory.
/content/20262027-UE-DataMining-Project/20262027-UE-DataMining-Project

In [92]:
!git pull

Already up to date.

**Ecology**

**Health**

# 1. Chargement et première exploration du jeu de données

Nous commençons par charger le fichier `cardiac_recordings.csv`, situé dans le dossier `data/health/` du projet.

L’objectif de cette première étape est de comprendre la **structure générale du jeu de données** avant toute opération de nettoyage :

- le nombre d’observations ;
- le nombre de variables ;
- le contenu des colonnes ;
- les types de données.

In [93]:
import pandas as pd

df = pd.read_csv("data/health/cardiac_recordings.csv")

Nous vérifions ensuite les **dimensions du jeu de données** afin de connaître :

- le nombre de lignes ;
- le nombre de colonnes.

In [94]:
df.shape

(44, 19)

Le jeu de données contient 44 observations et 19 variables.

### Aperçu des premières observations

Nous affichons les premières lignes du jeu de données afin d’obtenir un premier aperçu de son contenu et de comprendre ce que représente une observation.

In [95]:
df.head()

,recording_id,patient_number,encounter_number,recording_date,recording_context,facility_license_number,reviewing_license_number,device_serial_number,device_model,sampling_rate_hz,sampling_interval_ms,duration_seconds,channel_count,sample_count,amplitude_unit,automated_interpretation,recording_notes_code,device_quality,archive_status
0,CRD-410031,PAT-31162,ENC-000004,2022-06-21,rest,FAC-VLN-101,LIC-VLN-RES-1016,DEV-CARD-07034,Vantage Rhythm Monitor,100,10,12.0,2,1200,normalized_unit,complex,rhythm_variability,80.9,finalized
1,CRD-410019,PAT-31162,ENC-000004,2022-06-21,technical_repeat,FAC-VLN-101,LIC-VLN-RES-1016,DEV-CARD-07044,HelixCard Duo,100,10,30.0,2,3000,normalized_unit,irregular,repeat_recommended,88.0,finalized
2,CRD-410025,PAT-31040,ENC-000007,2017-03-16,rest,FAC-AVL-201,LIC-VLN-MED-1003,DEV-CARD-07027,Asterion CV-3,125,8,12.0,2,1500,normalized_unit,review_required,no_note,84.8,finalized
3,CRD-410016,PAT-31115,ENC-000017,2025-09-11,rest,FAC-AVL-301,LIC-VLN-MED-1006,DEV-CARD-07019,Asterion CV-2,125,8,30.0,2,3750,normalized_unit,inconclusive,signal_overlap,86.7,finalized
4,CRD-410014,PAT-31233,ENC-000033,2023-04-25,rest,FAC-AVL-301,LIC-VLN-MED-1001,DEV-CARD-07022,HelixCard Duo,125,8,18.0,2,2250,normalized_unit,complex,rhythm_variability,93.0,finalized

In [96]:
%cd /content/20262027-UE-DataMining-Project

/content/20262027-UE-DataMining-Project

In [97]:
import os

os.listdir("data/health")

['clinical_notes.csv',
 'clinical_encounters.csv',
 'clinical_procedures.csv',
 'patient_administration.csv',
 'cardiac_signal_samples.csv',
 'clinical_observations.csv',
 'cardiac_recordings.csv']

In [98]:
import pandas as pd
import os

for fichier in os.listdir("data/health"):
    df_temp = pd.read_csv("data/health/" + fichier)

    print("\n==============================")
    print(fichier)
    print("Dimensions :", df_temp.shape)
    print("Colonnes :", list(df_temp.columns))

==============================
clinical_notes.csv
Dimensions : (30, 11)
Colonnes : ['document_id', 'patient_number', 'encounter_number', 'document_date', 'document_type', 'author_license_number', 'facility_license_number', 'title', 'text', 'confidentiality_class', 'superseded_document_id']

==============================
clinical_encounters.csv
Dimensions : (1069, 12)
Colonnes : ['encounter_number', 'patient_number', 'encounter_start', 'encounter_end', 'facility_license_number', 'encounter_type', 'referral_source', 'attending_license_number', 'service_unit', 'disposition', 'confidentiality_class', 'follow_up_date']

==============================
clinical_procedures.csv
Dimensions : (311, 14)
Colonnes : ['procedure_record_id', 'encounter_number', 'patient_number', 'procedure_code', 'procedure_description', 'scheduled_time', 'performed_time', 'performing_facility_license', 'performing_license_number', 'authorization_class', 'material_reference', 'procedure_status', 'outcome_code', 'next_review_date']

==============================
patient_administration.csv
Dimensions : (241, 10)
Colonnes : ['patient_number', 'family_name', 'given_name', 'date_of_birth', 'registered_sex', 'home_region', 'occupation_text', 'registration_date', 'primary_facility_license', 'record_status']

==============================
cardiac_signal_samples.csv
Dimensions : (96925, 4)
Colonnes : ['recording_id', 'time_ms', 'channel_a_normalized', 'channel_b_normalized']

==============================
clinical_observations.csv
Dimensions : (17736, 14)
Colonnes : ['observation_number', 'encounter_number', 'patient_number', 'observation_time', 'observation_code', 'observation_name', 'numeric_value', 'text_value', 'unit', 'reference_range_text', 'interpretation_code', 'device_reference', 'quality_code', 'assessor_license_number']

==============================
cardiac_recordings.csv
Dimensions : (44, 19)
Colonnes : ['recording_id', 'patient_number', 'encounter_number', 'recording_date', 'recording_context', 'facility_license_number', 'reviewing_license_number', 'device_serial_number', 'device_model', 'sampling_rate_hz', 'sampling_interval_ms', 'duration_seconds', 'channel_count', 'sample_count', 'amplitude_unit', 'automated_interpretation', 'recording_notes_code', 'device_quality', 'archive_status']

In [99]:
!git status

On branch main
Your branch is up to date with 'origin/main'.

Untracked files:
  (use "git add <file>..." to include in what will be committed)
	20262027-UE-DataMining-Project/

nothing added to commit but untracked files present (use "git add" to track)

In [100]:
!git remote -v

origin	https://github.com/Sheik-info/20262027-UE-DataMining-Project.git (fetch)
origin	https://github.com/Sheik-info/20262027-UE-DataMining-Project.git (push)

**Logistics**


On explore ici les jeux de données du dossier `data/logistics/` :
- `erp_facilities.csv` : les entrepôts / sites de l'entreprise
- `erp_business_partners.csv` : les partenaires (clients, fournisseurs, transporteurs...)
- `inventory_month_end.csv` : les stocks en fin de mois par site
- `inventory_adjustments.csv` : les ajustements manuels de stock
- `goods_receipts.csv` : les réceptions de marchandises
- `shipments.csv` : les expéditions
- `purchase_order_lines.csv` : les lignes de commandes d'achat

On commence, comme pour les autres parties, par un premier chargement et une exploration rapide avant de nettoyer quoi que ce soit.

 1. Chargement et première exploration
---

In [101]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import os
os.listdir("data/logistics")

['erp_business_partners.csv',
 'purchase_order_lines.csv',
 'erp_facilities.csv',
 'shipments.csv',
 'inventory_month_end.csv',
 'inventory_adjustments.csv',
 'goods_receipts.csv']

Avant de charger les fichiers, on regarde rapidement leurs dimensions et leurs colonnes.
Cela permet de vérifier la structure des données.

In [102]:
# Je regarde rapidement les fichiers avant de commencer
for fichier in os.listdir("data/logistics"):
    df = pd.read_csv("data/logistics/" + fichier)

    print("\n==============================")
    print(fichier)
    print("Dimensions :", df.shape)
    print("Colonnes :", list(df.columns))

==============================
erp_business_partners.csv
Dimensions : (80, 11)
Colonnes : ['partner_code', 'partner_name', 'partner_role', 'external_registration_number', 'billing_region', 'shipping_region', 'default_currency', 'payment_terms', 'partner_status', 'risk_class', 'onboarding_date']

==============================
purchase_order_lines.csv
Dimensions : (651, 16)
Colonnes : ['purchase_order_number', 'purchase_order_line', 'order_date', 'ordering_facility_code', 'supplier_partner_code', 'item_code', 'item_description', 'item_category', 'ordered_quantity', 'ordered_unit', 'unit_price', 'currency', 'requested_delivery_date', 'authorization_class', 'declared_cost_center', 'order_status']

==============================
erp_facilities.csv
Dimensions : (30, 11)
Colonnes : ['facility_code', 'facility_name', 'facility_category', 'operating_partner_code', 'street_address', 'region', 'latitude', 'longitude', 'opening_date', 'facility_status', 'storage_capabilities']

==============================
shipments.csv
Dimensions : (452, 16)
Colonnes : ['shipment_number', 'shipment_leg', 'dispatch_time', 'arrival_time', 'sender_partner_code', 'receiver_partner_code', 'origin_facility_code', 'destination_facility_code', 'carrier_partner_code', 'item_category', 'declared_quantity', 'declared_unit', 'temperature_control_class', 'authorization_class', 'declared_purpose', 'shipment_status']

==============================
inventory_month_end.csv
Dimensions : (502, 11)
Colonnes : ['facility_code', 'reporting_month', 'item_category', 'opening_stock', 'received_quantity', 'outgoing_quantity', 'documented_internal_use', 'documented_waste', 'closing_stock', 'unit', 'inventory_status']

==============================
inventory_adjustments.csv
Dimensions : (140, 11)
Colonnes : ['adjustment_number', 'facility_code', 'adjustment_date', 'item_category', 'adjustment_quantity', 'unit', 'adjustment_reason', 'approved_by_role', 'related_receipt_number', 'related_shipment_number', 'adjustment_status']

==============================
goods_receipts.csv
Dimensions : (612, 12)
Colonnes : ['receipt_number', 'purchase_order_number', 'purchase_order_line', 'receipt_date', 'receiving_facility_code', 'supplier_partner_code', 'received_quantity', 'received_unit', 'batch_reference', 'inspection_status', 'storage_location_code', 'receipt_status']

Les 7 fichiers sont chargés séparément afin de faciliter leur manipulation et leur analyse.

In [103]:
df_fac = pd.read_csv("data/logistics/erp_facilities.csv")
df_bp = pd.read_csv("data/logistics/erp_business_partners.csv")
df_invm = pd.read_csv("data/logistics/inventory_month_end.csv")
df_inva = pd.read_csv("data/logistics/inventory_adjustments.csv")
df_rcv = pd.read_csv("data/logistics/goods_receipts.csv")
df_shp = pd.read_csv("data/logistics/shipments.csv")
df_po = pd.read_csv("data/logistics/purchase_order_lines.csv")

In [104]:
dfs = {
    "facilities": df_fac,
    "business_partners": df_bp,
    "inventory_month_end": df_invm,
    "inventory_adjustments": df_inva,
    "goods_receipts": df_rcv,
    "shipments": df_shp,
    "purchase_order_lines": df_po
}

In [105]:
df_fac.head()

,facility_code,facility_name,facility_category,operating_partner_code,street_address,region,latitude,longitude,opening_date,facility_status,storage_capabilities
0,FCL-1011,Meridian Valenne Headquarters,office,BP-30078,"Meridian Valenne Headquarters, Valenne Central...",Valenne Central District,47.24,7.58,2006-01-01,active,ambient
1,FCL-1024,Meridian Kintara Biological Aggregation Facility,warehouse,BP-30078,Meridian Kintara Biological Aggregation Facili...,Kintara Karst Cluster,4.74,112.28,1997-01-01,active,ambient;secure_cage;2-8C;frozen
2,FCL-1019,Meridian Avelora Transfer Annex,transfer_hub,BP-30078,"Meridian Avelora Transfer Annex, Eastern Avelo...",Eastern Avelora Agricultural Cluster,7.46,101.91,2003-01-01,active,ambient;secure_cage;2-8C;frozen
3,FCL-1020,Meridian Tembara Coastal Hub,transfer_hub,BP-30078,"Meridian Tembara Coastal Hub, Tembara Coastal ...",Tembara Coastal Cluster,2.20,104.55,2010-01-01,active,ambient;secure_cage;2-8C;frozen
4,FCL-1016,Northstar Tembara Cold-Chain Hub,warehouse,BP-30047,"Northstar Tembara Cold-Chain Hub, Tembara Coas...",Tembara Coastal Cluster,2.23,104.58,2008-01-01,active,ambient;secure_cage;2-8C;frozen

Un aperçu des premières lignes est affiché afin de vérifier la structure et le contenu des données.

In [106]:
df_po.head()

,purchase_order_number,purchase_order_line,order_date,ordering_facility_code,supplier_partner_code,item_code,item_description,item_category,ordered_quantity,ordered_unit,unit_price,currency,requested_delivery_date,authorization_class,declared_cost_center,order_status
0,PO-2014-00001,1,2014-06-24,FCL-1007,BP-30078,ITM-MED-001,General clinical consumable case,medical_consumables,73,case,157.85,VLN,2014-07-08,restricted,Clinical Programmes,completed
1,PO-2015-00001,1,2015-01-22,FCL-1010,BP-30068,ITM-TRN-001,Regional refrigerated transport service,transport_service,1,service,3482.27,VLN,2015-02-01,ordinary,Clinical Services,completed
2,PO-2015-00002,1,2015-01-29,FCL-1030,BP-30066,ITM-COM-001,Secure communication service,communication_service,1,service,1292.19,KRN,2015-02-26,ordinary,General Operations,completed
3,PO-2015-00003,1,2015-02-10,FCL-1010,BP-30080,ITM-LAB-002,Sample preparation material pack,laboratory_material,3,pack,458.67,VLN,2015-03-02,expedited,Clinical Services,completed
4,PO-2015-00004,1,2015-02-12,FCL-1022,BP-30021,ITM-GRA-001,Programme grant transfer,grant,1,grant,26933.28,KRN,2015-02-21,ordinary,Facilities,completed

Les types des colonnes sont vérifiés afin de repérer les données qui ne sont pas dans le format attendu.

In [107]:
for nom, df in dfs.items():
    print("\n=======================")
    print(nom)
    print(df.dtypes)

=======================
facilities
facility_code              object
facility_name              object
facility_category          object
operating_partner_code     object
street_address             object
region                     object
latitude                  float64
longitude                 float64
opening_date               object
facility_status            object
storage_capabilities       object
dtype: object

=======================
business_partners
partner_code                    object
partner_name                    object
partner_role                    object
external_registration_number    object
billing_region                  object
shipping_region                 object
default_currency                object
payment_terms                   object
partner_status                  object
risk_class                      object
onboarding_date                 object
dtype: object

=======================
inventory_month_end
facility_code               object
reporting_month             object
item_category               object
opening_stock               object
received_quantity           object
outgoing_quantity           object
documented_internal_use    float64
documented_waste            object
closing_stock               object
unit                        object
inventory_status            object
dtype: object

=======================
inventory_adjustments
adjustment_number          object
facility_code              object
adjustment_date            object
item_category              object
adjustment_quantity        object
unit                       object
adjustment_reason          object
approved_by_role           object
related_receipt_number     object
related_shipment_number    object
adjustment_status          object
dtype: object

=======================
goods_receipts
receipt_number             object
purchase_order_number      object
purchase_order_line         int64
receipt_date               object
receiving_facility_code    object
supplier_partner_code      object
received_quantity          object
received_unit              object
batch_reference            object
inspection_status          object
storage_location_code      object
receipt_status             object
dtype: object

=======================
shipments
shipment_number              object
shipment_leg                  int64
dispatch_time                object
arrival_time                 object
sender_partner_code          object
receiver_partner_code        object
origin_facility_code         object
destination_facility_code    object
carrier_partner_code         object
item_category                object
declared_quantity             int64
declared_unit                object
temperature_control_class    object
authorization_class          object
declared_purpose             object
shipment_status              object
dtype: object

=======================
purchase_order_lines
purchase_order_number      object
purchase_order_line         int64
order_date                 object
ordering_facility_code     object
supplier_partner_code      object
item_code                  object
item_description           object
item_category              object
ordered_quantity           object
ordered_unit               object
unit_price                 object
currency                   object
requested_delivery_date    object
authorization_class        object
declared_cost_center       object
order_status               object
dtype: object

In [108]:
for nom, df in dfs.items():
    print("\n---", nom, "---")

    for colonne in df.columns:
        nb = df[colonne].isna().sum()
        if nb > 0:
            print(colonne, ":", nb)

--- facilities ---
storage_capabilities : 1

--- business_partners ---
external_registration_number : 14
billing_region : 1

--- inventory_month_end ---

--- inventory_adjustments ---
approved_by_role : 1
related_receipt_number : 117
related_shipment_number : 103

--- goods_receipts ---
inspection_status : 4

--- shipments ---
arrival_time : 17

--- purchase_order_lines ---
declared_cost_center : 3

Certaines colonnes contenant des quantités et des prix sont actuellement au format `object`. Elles devront être converties dans un format numérique avant de poursuivre l'analyse.

 2. Nettoyage

---

#### 2.1 Lignes dupliquées

La présence de lignes dupliquées est vérifiée dans chaque fichier.

In [109]:
for nom, df in dfs.items():
    print(nom, ":", df.duplicated().sum(), "doublon(s)")

facilities : 0 doublon(s)
business_partners : 0 doublon(s)
inventory_month_end : 2 doublon(s)
inventory_adjustments : 0 doublon(s)
goods_receipts : 2 doublon(s)
shipments : 2 doublon(s)
purchase_order_lines : 1 doublon(s)

##### Suppression des doublons

In [110]:
df_invm = df_invm.drop_duplicates().reset_index(drop=True)
df_rcv = df_rcv.drop_duplicates().reset_index(drop=True)
df_shp = df_shp.drop_duplicates().reset_index(drop=True)
df_po = df_po.drop_duplicates().reset_index(drop=True)

dfs["inventory_month_end"] = df_invm
dfs["goods_receipts"] = df_rcv
dfs["shipments"] = df_shp
dfs["purchase_order_lines"] = df_po

for nom, df in dfs.items():
    print(nom, ":", df.shape[0], "lignes")

facilities : 30 lignes
business_partners : 80 lignes
inventory_month_end : 500 lignes
inventory_adjustments : 140 lignes
goods_receipts : 610 lignes
shipments : 450 lignes
purchase_order_lines : 650 lignes

##### 2.2 Colonnes constantes

Les colonnes qui contiennent une seule valeur, ou qui sont entièrement vides, sont repérées. Elles n'apportent pas de variation pour l'analyse et peuvent donc être supprimées.

In [111]:
for nom, df in dfs.items():
    cols_constantes = [c for c in df.columns if df[c].nunique(dropna=False) <= 1]

    if cols_constantes:
        print(nom, ":", cols_constantes)

facilities : ['facility_status']
goods_receipts : ['purchase_order_line']
shipments : ['shipment_leg']
purchase_order_lines : ['purchase_order_line']

Suppression des colonnes qui ne varient pas

In [112]:
df_fac = df_fac.drop(columns=["facility_status"])

df_rcv = df_rcv.drop(columns=["purchase_order_line"])
df_po = df_po.drop(columns=["purchase_order_line"])

df_shp = df_shp.drop(columns=["shipment_leg"])

dfs["facilities"] = df_fac
dfs["goods_receipts"] = df_rcv
dfs["purchase_order_lines"] = df_po
dfs["shipments"] = df_shp

#### 2.3 Nettoyage des colonnes numériques — inventory_month_end

Les colonnes `opening_stock`, `received_quantity`, `outgoing_quantity`, `documented_waste` et `closing_stock` sont actuellement de type `object` alors qu'elles devraient être numériques. Deux problèmes de format sont en cause :

- certaines valeurs utilisent une virgule comme séparateur décimal (ex : `"5,42"`) au lieu d'un point ;
- certaines valeurs contiennent l'unité collée au nombre (ex : `"14.55 sealed_lot"`). Cette unité est redondante avec la colonne `unit` déjà présente, elle peut donc être retirée sans perte d'information.

Une fonction de nettoyage est appliquée à ces colonnes.

In [113]:
import re

def nettoyer_colonne_numerique(serie):
    s = serie.astype(str).str.strip()
    s = s.str.replace(',', '.', regex=False)
    s = s.str.extract(r'(-?\d+\.?\d*)')[0]
    return pd.to_numeric(s, errors='coerce')

colonnes_a_nettoyer = ['opening_stock', 'received_quantity', 'outgoing_quantity',
                        'documented_waste', 'closing_stock']

for col in colonnes_a_nettoyer:
    df_invm[col] = nettoyer_colonne_numerique(df_invm[col])

df_invm.dtypes

facility_code               object
reporting_month             object
item_category               object
opening_stock              float64
received_quantity          float64
outgoing_quantity          float64
documented_internal_use    float64
documented_waste           float64
closing_stock              float64
unit                        object
inventory_status            object
dtype: object

La colonne `inventory_status` présente aussi une incohérence de casse (`"closed"` / `"CLOSED"`, `"provisional"` / `"PROVISIONAL"`). Elle est uniformisée en minuscules.

In [114]:
df_invm['inventory_status'] = df_invm['inventory_status'].str.lower()
df_invm['inventory_status'].value_counts()

inventory_status
closed         444
provisional     38
revised         18
Name: count, dtype: int64

##### Vérification de cohérence comptable

Le stock de fin de mois (`closing_stock`) devrait théoriquement correspondre à :
`opening_stock + received_quantity − outgoing_quantity − documented_internal_use − documented_waste`.

Un écart entre valeur déclarée et valeur recalculée est ajouté comme nouvelle colonne, afin d'être analysé plus tard plutôt que d'être corrigé arbitrairement.

In [115]:
dfs["inventory_month_end"] = df_invm

In [116]:
df_invm.dtypes

facility_code               object
reporting_month             object
item_category               object
opening_stock              float64
received_quantity          float64
outgoing_quantity          float64
documented_internal_use    float64
documented_waste           float64
closing_stock              float64
unit                        object
inventory_status            object
dtype: object

In [117]:
df_invm.head()

,facility_code,reporting_month,item_category,opening_stock,received_quantity,outgoing_quantity,documented_internal_use,documented_waste,closing_stock,unit,inventory_status
0,FCL-1024,2018-02-01,biological_sample,14.55,5.46,0.00,0.49,0.22,16.24,sealed_lot,closed
1,FCL-1024,2018-03-01,biological_sample,16.24,5.00,0.00,1.94,0.65,0.55,sealed_lot,closed
2,FCL-1024,2018-05-01,biological_sample,0.55,0.00,0.00,0.00,0.36,0.17,sealed_lot,closed
3,FCL-1024,2019-01-01,biological_sample,0.17,0.00,1.37,0.00,0.02,0.00,sealed_lot,provisional
4,FCL-1024,2019-08-01,biological_sample,0.00,3.12,8.80,0.00,0.08,0.00,sealed_lot,closed

#### 2.4 Nettoyage des colonnes numériques — goods_receipts

La colonne `received_quantity` présente les mêmes problèmes de format que `inventory_month_end` : virgule décimale et unité collée à la valeur (redondante avec `received_unit`). La même fonction de nettoyage est réutilisée.

In [118]:
df_rcv['received_quantity'] = nettoyer_colonne_numerique(df_rcv['received_quantity'])
df_rcv['received_quantity'].describe()

count    610.000000
mean      20.591770
std       22.947117
min        0.780000
25%        1.000000
50%       13.000000
75%       29.000000
max       90.000000
Name: received_quantity, dtype: float64

La colonne `receipt_status` présente une incohérence de casse (`"posted"` / `"POSTED"`), uniformisée en minuscules.

In [119]:
df_rcv['receipt_status'] = df_rcv['receipt_status'].str.lower()
df_rcv['receipt_status'].value_counts()

receipt_status
posted          576
quality_hold     34
Name: count, dtype: int64

4 lignes présentent une valeur manquante pour `inspection_status`, toutes avec un `receipt_status` égal à `"posted"`. Plutôt que de supposer une valeur, ces cas sont rendus explicites avec la catégorie `"non_renseigne"`.

In [120]:
df_rcv['inspection_status'] = df_rcv['inspection_status'].fillna('non_renseigne')
df_rcv['inspection_status'].value_counts()

inspection_status
accepted         505
conditional       67
held              34
non_renseigne      4
Name: count, dtype: int64

In [121]:
dfs["goods_receipts"] = df_rcv

In [122]:
df_rcv.dtypes

receipt_number              object
purchase_order_number       object
receipt_date                object
receiving_facility_code     object
supplier_partner_code       object
received_quantity          float64
received_unit               object
batch_reference             object
inspection_status           object
storage_location_code       object
receipt_status              object
dtype: object

In [123]:
df_rcv.head()

,receipt_number,purchase_order_number,receipt_date,receiving_facility_code,supplier_partner_code,received_quantity,received_unit,batch_reference,inspection_status,storage_location_code,receipt_status
0,RCV-2014-00001,PO-2014-00001,2014-07-08,FCL-1007,BP-30078,73.0,case,B-2014-44545,held,BIN-35,quality_hold
1,RCV-2015-00002,PO-2015-00001,2015-02-02,FCL-1010,BP-30068,0.9,service,B-2015-58495,accepted,BIN-36,posted
2,RCV-2015-00003,PO-2015-00002,2015-02-28,FCL-1030,BP-30066,1.0,service,B-2015-48474,held,BIN-17,quality_hold
3,RCV-2015-00004,PO-2015-00003,2015-03-02,FCL-1010,BP-30080,3.0,pack,B-2015-71913,accepted,BIN-16,posted
4,RCV-2015-00005,PO-2015-00004,2015-02-21,FCL-1022,BP-30021,1.0,grant,B-2015-31154,accepted,BIN-42,posted

#### 2.5 Nettoyage des colonnes numériques — purchase_order_lines

Les colonnes `ordered_quantity` (unité collée) et `unit_price` (virgule décimale) présentent les mêmes problèmes de format que les fichiers précédents.

In [124]:
df_po['ordered_quantity'] = nettoyer_colonne_numerique(df_po['ordered_quantity'])
df_po['unit_price'] = nettoyer_colonne_numerique(df_po['unit_price'])
df_po[['ordered_quantity', 'unit_price']].describe()

       ordered_quantity    unit_price
count        650.000000    650.000000
mean          20.964615   3844.168754
std           23.136234   5701.539177
min            1.000000     83.810000
25%            1.000000    560.435000
50%           14.000000   1600.670000
75%           30.000000   4243.115000
max           90.000000  28663.740000

La colonne `item_category` présente des doublons de casse (ex : `"monitoring_equipment"` / `"MONITORING_EQUIPMENT"`), uniformisés en minuscules.

In [125]:
df_po['item_category'] = df_po['item_category'].str.lower()
df_po['item_category'].value_counts()

item_category
medical_consumables       79
monitoring_equipment      57
cold_storage_equipment    54
agricultural_product      53
protective_equipment      49
laboratory_material       44
biological_sample         42
office_supply             37
transport_service         33
other                     33
refrigeration_service     29
consulting_service        25
agricultural_equipment    23
legal_service             22
research_contract         22
medical_equipment         20
communication_service     17
grant                     11
Name: count, dtype: int64

3 lignes présentent une valeur manquante pour `declared_cost_center`, sans motif apparent. Comme pour `inspection_status`, ces cas sont rendus explicites avec la catégorie `"non_renseigne"` plutôt que de supposer une valeur.

In [126]:
df_po['declared_cost_center'] = df_po['declared_cost_center'].fillna('non_renseigne')
df_po['declared_cost_center'].value_counts()

declared_cost_center
Field Programmes             98
Clinical Services            93
Research Services            90
Agricultural Distribution    87
General Operations           84
Facilities                   81
Cold Chain                   70
Clinical Programmes          26
Field Operations             18
non_renseigne                 3
Name: count, dtype: int64

**Point de vigilance pour l'analyse** : `unit_price` est exprimé dans 5 devises différentes (VLN, AVL, TMB, NDH, KRN). Toute comparaison  de prix entre commandes nécessitera une standardisation (a faire plus tard)

In [127]:
dfs["purchase_order_lines"] = df_po

In [128]:
df_po.head()

,purchase_order_number,order_date,ordering_facility_code,supplier_partner_code,item_code,item_description,item_category,ordered_quantity,ordered_unit,unit_price,currency,requested_delivery_date,authorization_class,declared_cost_center,order_status
0,PO-2014-00001,2014-06-24,FCL-1007,BP-30078,ITM-MED-001,General clinical consumable case,medical_consumables,73,case,157.85,VLN,2014-07-08,restricted,Clinical Programmes,completed
1,PO-2015-00001,2015-01-22,FCL-1010,BP-30068,ITM-TRN-001,Regional refrigerated transport service,transport_service,1,service,3482.27,VLN,2015-02-01,ordinary,Clinical Services,completed
2,PO-2015-00002,2015-01-29,FCL-1030,BP-30066,ITM-COM-001,Secure communication service,communication_service,1,service,1292.19,KRN,2015-02-26,ordinary,General Operations,completed
3,PO-2015-00003,2015-02-10,FCL-1010,BP-30080,ITM-LAB-002,Sample preparation material pack,laboratory_material,3,pack,458.67,VLN,2015-03-02,expedited,Clinical Services,completed
4,PO-2015-00004,2015-02-12,FCL-1022,BP-30021,ITM-GRA-001,Programme grant transfer,grant,1,grant,26933.28,KRN,2015-02-21,ordinary,Facilities,completed

#### 2.6 Nettoyage des colonnes — inventory_adjustments

`adjustment_quantity` présente une unité collée sur une ligne (redondante avec `unit`), retirée avec la même fonction que précédemment.

In [129]:
df_inva['adjustment_quantity'] = nettoyer_colonne_numerique(df_inva['adjustment_quantity'])
df_inva['adjustment_quantity'].describe()

count    140.000000
mean      -0.598857
std        3.995308
min       -7.910000
25%       -3.035000
50%       -1.805000
75%        2.005000
max        7.870000
Name: adjustment_quantity, dtype: float64

`adjustment_reason` présente des doublons de casse, uniformisés en minuscules.

In [130]:
df_inva['adjustment_reason'] = df_inva['adjustment_reason'].str.lower()
df_inva['adjustment_reason'].value_counts()

adjustment_reason
transfer posting correction    24
cycle count correction         23
quality-hold release           21
damaged packaging write-off    16
unit-of-measure review         12
specialist programme issue     11
procedure stock issue          10
late receipt posting            9
controlled-area consumption     9
cycle count reconciliation      5
Name: count, dtype: int64

In [131]:
df_inva['approved_by_role'] = df_inva['approved_by_role'].fillna('non_renseigne')

**Observation** : `related_receipt_number` et `related_shipment_number` sont laissés tels quels (valeurs manquantes conservées), car l'absence des deux (85 lignes) correspond probablement à des ajustements sans document source lié.

In [132]:
dfs["inventory_adjustments"] = df_inva

In [133]:
df_inva.head()

,adjustment_number,facility_code,adjustment_date,item_category,adjustment_quantity,unit,adjustment_reason,approved_by_role,related_receipt_number,related_shipment_number,adjustment_status
0,ADJ-2014-00001,FCL-1007,2014-07-18,medical_consumables,-1.58,case,specialist programme issue,clinical stores manager,NaN,NaN,posted
1,ADJ-2015-00002,FCL-1007,2015-09-10,medical_consumables,-2.70,case,specialist programme issue,specialist programme administrator,NaN,NaN,posted
2,ADJ-2015-00003,FCL-1024,2015-10-30,monitoring_equipment,3.68,kit,late receipt posting,warehouse manager,RCV-2022-00361,NaN,posted
3,ADJ-2016-00004,FCL-1007,2016-01-20,biological_sample,6.52,sealed_lot,late receipt posting,finance controller,NaN,NaN,pending_review
4,ADJ-2016-00005,FCL-1010,2016-02-18,medical_consumables,-2.43,case,procedure stock issue,quality manager,NaN,NaN,posted

#### 2.7 Nettoyage — erp_facilities
 Ce fichier ne présente pas de problème de format numérique ni de casse. Seule la colonne storage_capabilities contient une valeur manquante

In [134]:
df_fac['storage_capabilities'] = df_fac['storage_capabilities'].fillna('non_renseigne')
df_fac['storage_capabilities'].value_counts()

storage_capabilities
ambient;secure_cage                9
ambient;secure_cage;2-8C;frozen    8
ambient                            6
2-8C;controlled_access             6
non_renseigne                      1
Name: count, dtype: int64

mise à jour du dic

In [135]:
dfs["facilities"] = df_fac
df_fac.head()

,facility_code,facility_name,facility_category,operating_partner_code,street_address,region,latitude,longitude,opening_date,storage_capabilities
0,FCL-1011,Meridian Valenne Headquarters,office,BP-30078,"Meridian Valenne Headquarters, Valenne Central...",Valenne Central District,47.24,7.58,2006-01-01,ambient
1,FCL-1024,Meridian Kintara Biological Aggregation Facility,warehouse,BP-30078,Meridian Kintara Biological Aggregation Facili...,Kintara Karst Cluster,4.74,112.28,1997-01-01,ambient;secure_cage;2-8C;frozen
2,FCL-1019,Meridian Avelora Transfer Annex,transfer_hub,BP-30078,"Meridian Avelora Transfer Annex, Eastern Avelo...",Eastern Avelora Agricultural Cluster,7.46,101.91,2003-01-01,ambient;secure_cage;2-8C;frozen
3,FCL-1020,Meridian Tembara Coastal Hub,transfer_hub,BP-30078,"Meridian Tembara Coastal Hub, Tembara Coastal ...",Tembara Coastal Cluster,2.20,104.55,2010-01-01,ambient;secure_cage;2-8C;frozen
4,FCL-1016,Northstar Tembara Cold-Chain Hub,warehouse,BP-30047,"Northstar Tembara Cold-Chain Hub, Tembara Coas...",Tembara Coastal Cluster,2.23,104.58,2008-01-01,ambient;secure_cage;2-8C;frozen

###2.8 Nettoyage — erp_business_partners
partner_role présente une incohérence de casse ("Supplier" / "supplier"), comme observé précédemment pour item_category dans purchase_order_lines. Elle est uniformisée en minuscules.

In [136]:
df_bp['partner_role'] = df_bp['partner_role'].str.lower()
df_bp['partner_role'].value_counts()

partner_role
customer             32
service_partner      19
supplier             14
carrier               9
supplier_customer     6
Name: count, dtype: int64

external_registration_number (14 valeurs manquantes) et billing_region (1 valeur manquante) ne présentent pas de motif apparent expliquant leur absence. Ces cas sont rendus explicites avec la catégorie "non_renseigne", dans la continuité de la démarche adoptée pour les autres fichiers

In [137]:
df_bp['external_registration_number'] = df_bp['external_registration_number'].fillna('non_renseigne')
df_bp['billing_region'] = df_bp['billing_region'].fillna('non_renseigne')

Point de vigilance pour l'analyse : la colonne shipping_region mélange deux granularités géographiques différentes (ex : "Valenne Central District" face à "Valenne Republic"). Cette hétérogénéité n'est pas corrigée ici mais devra être prise en compte lors d'agrégations géographiques (à faire lors de l'analyse)

In [138]:
dfs["business_partners"] = df_bp
df_bp.head()

,partner_code,partner_name,partner_role,external_registration_number,billing_region,shipping_region,default_currency,payment_terms,partner_status,risk_class,onboarding_date
0,BP-30001,Marula Cold Store Cooperative,supplier_customer,REG-AVL-20012,Avelora Federation,Eastern Avelora Agricultural Cluster,AVL,NET45,active,review,2001-02-01
1,BP-30002,Blue Heron Monitoring Cooperative,customer,REG-KNT-20037,Kintara Republic,Kintara Karst Cluster,KRN,NET45,active,standard,2012-03-01
2,BP-30003,Orra Technical Services,supplier,REG-AVL-20022,Avelora Federation,Eastern Avelora Agricultural Cluster,AVL,PUBLIC30,active,review,2008-04-01
3,BP-30004,Common Ground Climate Forum,service_partner,REG-VLN-01008,Valenne Republic,Valenne Central District,VLN,PREPAID,active,review,2014-05-01
4,BP-30005,Warden Medical Ventures,service_partner,REG-VLN-01016,Valenne Republic,Valenne Republic,VLN,PREPAID,inactive,standard,2013-06-01

###2.9 Nettoyage — shipments

Les doublons et la colonne constante (shipment_leg) ont déjà été traités dans les étapes 2.1 et 2.2. Il reste des incohérences de casse sur deux colonnes catégorielles, un problème d'espaces multiples sur une troisième, et des valeurs manquantes sur arrival_time.

In [139]:
df_shp['temperature_control_class'] = df_shp['temperature_control_class'].str.lower()
df_shp['shipment_status'] = df_shp['shipment_status'].str.lower()

df_shp['temperature_control_class'].value_counts()

temperature_control_class
ambient    343
2-8c       103
frozen       4
Name: count, dtype: int64

In [140]:
df_shp['shipment_status'].value_counts()

shipment_status
delivered     385
delayed        34
in_transit     17
returned       14
Name: count, dtype: int64

declared_purpose présente un problème différent des cas précédents : certaines valeurs contiennent des espaces multiples ou en début de chaîne (ex : " laboratory delivery" au lieu de "laboratory delivery"), ce qui crée artificiellement de fausses catégories distinctes. Une fonction dédiée est utilisée pour normaliser les espaces, sur le même principe que nettoyer_colonne_numerique.

In [141]:
def nettoyer_espaces(serie):
    s = serie.astype(str).str.strip()
    s = s.str.replace(r'\s+', ' ', regex=True)
    return s

df_shp['declared_purpose'] = nettoyer_espaces(df_shp['declared_purpose'])
df_shp['declared_purpose'].value_counts()

declared_purpose
scheduled stock transfer                              74
laboratory delivery                                   72
field programme support                               72
customer distribution                                 64
facility replenishment                                64
agricultural distribution                             60
temperature-controlled clinical programme delivery    26
environmental and wildlife reference materials        18
Name: count, dtype: int64

vérification, pas de modification

In [142]:
df_shp[df_shp['arrival_time'].isna()]['shipment_status'].value_counts()

shipment_status
in_transit    17
Name: count, dtype: int64

mise à jour du dict

In [143]:
dfs["shipments"] = df_shp
df_shp.head()

,shipment_number,dispatch_time,arrival_time,sender_partner_code,receiver_partner_code,origin_facility_code,destination_facility_code,carrier_partner_code,item_category,declared_quantity,declared_unit,temperature_control_class,authorization_class,declared_purpose,shipment_status
0,SHP-2014-00001,2014-07-10T09:00:00,2014-07-11T03:00:00,BP-30078,BP-30021,FCL-1011,FCL-1007,BP-30047,biological_sample,2,sealed_lot,2-8c,expedited,temperature-controlled clinical programme deli...,delivered
1,SHP-2015-00001,2015-01-10T11:00:00,2015-01-13T16:00:00,BP-30035,BP-30033,FCL-1009,FCL-1013,BP-30020,medical_consumables,73,case,2-8c,ordinary,scheduled stock transfer,returned
2,SHP-2015-00002,2015-01-11T06:00:00,2015-01-12T00:00:00,BP-30028,BP-30037,FCL-1020,FCL-1017,BP-30015,office_supply,82,case,ambient,emergency,customer distribution,delivered
3,SHP-2015-00003,2015-02-17T15:00:00,2015-02-19T08:00:00,BP-30056,BP-30078,FCL-1019,FCL-1011,BP-30047,biological_sample,2,sealed_lot,2-8c,restricted,laboratory delivery,delivered
4,SHP-2015-00004,2015-06-10T12:00:00,2015-06-12T09:00:00,BP-30025,BP-30079,FCL-1026,FCL-1022,BP-30025,legal_service,1,service,ambient,ordinary,facility replenishment,delivered

In [144]:
#simple verif
for nom, df in dfs.items():
    print(nom, ":", df.shape)

facilities : (30, 10)
business_partners : (80, 11)
inventory_month_end : (500, 11)
inventory_adjustments : (140, 11)
goods_receipts : (610, 11)
shipments : (450, 15)
purchase_order_lines : (650, 15)

#### Bilan nettoyage — logistics

On a nettoyé les 7 fichiers un par un en suivant à chaque fois la même logique :

- on a supprimé les doublons (lignes identiques) et les colonnes qui ne varient jamais (ex : `facility_status`, `shipment_leg`), elles ne servent à rien pour l'analyse
- on a corrigé les colonnes numériques qui étaient stockées en texte (virgule au lieu de point, unité collée genre "12kg"), avec la fonction `nettoyer_colonne_numerique`
- on a uniformisé les catégories qui avaient des soucis de casse (ex : "Supplier" vs "supplier", "DELIVERED" vs "delivered"), en mettant tout en minuscules
- pour les valeurs manquantes, on a essayé à chaque fois de comprendre pourquoi elles étaient manquantes avant de faire quoi que ce soit. Quand on n'avait pas d'explication, on a préféré les marquer clairement comme `"non_renseigne"` plutôt que d'inventer une valeur. Et quand l'absence avait un sens (ex : pas de `arrival_time` parce que le colis est encore `in_transit`), on l'a laissée telle quelle

**Trucs à garder en tête pour la suite** :
- `unit_price` est dans 5 devises différentes, donc pas comparable tel quel entre commandes
- `shipping_region` mélange des noms de région et des noms de pays, à uniformiser avant de faire des stats dessus

**Ce qu'il reste à faire** : on n'a pas encore regardé les valeurs aberrantes (outliers) dans les colonnes numériques, c'est la prochaine étape avant de dire que le nettoyage logistics est vraiment terminé.

**Public records**

In [145]:
df_pr = pd.read_csv("data/public_records/institutional_memos.csv")  #à finir quand on saura faire les textes

In [146]:
print(df_pr.head())

# Valeurs manquantes
print(df_pr.isna().sum())

# Nombre de valeurs uniques
print(df_pr.nunique())

  document_id document_date          document_type     author_name  \
0  MEM-510062    2024-04-30  inventory_explanation      Soren Kade
1  MEM-510100    2023-08-17   security_instruction      Soren Kade
2  MEM-510101    2025-03-14         meeting_record      Soren Kade
3  MEM-510128    2018-05-15    internal_memorandum  Adrian Vosmere
4  MEM-510069    2021-10-22    internal_memorandum  Dr. Elias Voss

     author_organization                              recipient_text  \
0  Meridian BioLogistics  Restricted operations and compliance group
1  Meridian BioLogistics  Restricted operations and compliance group
2  Meridian BioLogistics  Restricted operations and compliance group
3    Vosmere Biotechnics         Operations, finance, and compliance
4  Meridian BioLogistics         Operations, finance, and compliance

                                  subject_line  \
0         April Biological-Unit Reconciliation
1  Secure Delivery Record-Handling Instruction
2        Restricted CHAMELEO Governance Review
3            Internal Operations Memorandum 56
4        Internal  Operations  Memorandum  57

                                                text related_purchase_order  \
0  SUBJECT\nUnresolved biological-unit imbalance ...                    NaN
1  SCOPE\nThis instruction applies to staff handl...                    NaN
2  MEETING RECORD — RESTRICTED GOVERNANCE REVIEW\...                    NaN
3  SUBJECT\nOperational review of cold-chain reco...                    NaN
4  SUBJECT\nOperational review of supplier onboar...                    NaN

  related_shipment_number related_case_number visibility_level
0                     NaN                 NaN       restricted
1          SHP-2022-00011                 NaN       restricted
2          SHP-2023-00035                 NaN       restricted
3          SHP-2020-00019                 NaN       restricted
4                     NaN                 NaN         internal
document_id                 0
document_date               0
document_type               0
author_name                 0
author_organization         0
recipient_text              0
subject_line                0
text                        0
related_purchase_order     25
related_shipment_number    22
related_case_number        20
visibility_level            0
dtype: int64
document_id                30
document_date              30
document_type               6
author_name                27
author_organization        13
recipient_text              2
subject_line               30
text                       30
related_purchase_order      5
related_shipment_number     8
related_case_number         8
visibility_level            3
dtype: int64

In [147]:
print(df_pr.head())

# Valeurs manquantes
print(df_pr.isna().sum())

# Nombre de valeurs uniques
print(df_pr.nunique())

  document_id document_date          document_type     author_name  \
0  MEM-510062    2024-04-30  inventory_explanation      Soren Kade
1  MEM-510100    2023-08-17   security_instruction      Soren Kade
2  MEM-510101    2025-03-14         meeting_record      Soren Kade
3  MEM-510128    2018-05-15    internal_memorandum  Adrian Vosmere
4  MEM-510069    2021-10-22    internal_memorandum  Dr. Elias Voss

     author_organization                              recipient_text  \
0  Meridian BioLogistics  Restricted operations and compliance group
1  Meridian BioLogistics  Restricted operations and compliance group
2  Meridian BioLogistics  Restricted operations and compliance group
3    Vosmere Biotechnics         Operations, finance, and compliance
4  Meridian BioLogistics         Operations, finance, and compliance

                                  subject_line  \
0         April Biological-Unit Reconciliation
1  Secure Delivery Record-Handling Instruction
2        Restricted CHAMELEO Governance Review
3            Internal Operations Memorandum 56
4        Internal  Operations  Memorandum  57

                                                text related_purchase_order  \
0  SUBJECT\nUnresolved biological-unit imbalance ...                    NaN
1  SCOPE\nThis instruction applies to staff handl...                    NaN
2  MEETING RECORD — RESTRICTED GOVERNANCE REVIEW\...                    NaN
3  SUBJECT\nOperational review of cold-chain reco...                    NaN
4  SUBJECT\nOperational review of supplier onboar...                    NaN

  related_shipment_number related_case_number visibility_level
0                     NaN                 NaN       restricted
1          SHP-2022-00011                 NaN       restricted
2          SHP-2023-00035                 NaN       restricted
3          SHP-2020-00019                 NaN       restricted
4                     NaN                 NaN         internal
document_id                 0
document_date               0
document_type               0
author_name                 0
author_organization         0
recipient_text              0
subject_line                0
text                        0
related_purchase_order     25
related_shipment_number    22
related_case_number        20
visibility_level            0
dtype: int64
document_id                30
document_date              30
document_type               6
author_name                27
author_organization        13
recipient_text              2
subject_line               30
text                       30
related_purchase_order      5
related_shipment_number     8
related_case_number         8
visibility_level            3
dtype: int64

In [160]:
constant_cols = [
    col for col in df.columns
    if df_pr[col].nunique() <= 1
]

df_pr = df_pr.drop(columns=constant_cols)

In [161]:
for col in df_pr.select_dtypes(include="object").columns:
    print("\n---", col, "---")
    print("Nombre de catégories :", df_pr[col].nunique())
    print(df_pr[col].value_counts().head(10))

--- document_id ---
Nombre de catégories : 30
document_id
MEM-510062    1
MEM-510100    1
MEM-510101    1
MEM-510128    1
MEM-510069    1
MEM-510030    1
MEM-510080    1
MEM-510059    1
MEM-510074    1
MEM-510018    1
Name: count, dtype: int64

--- document_date ---
Nombre de catégories : 30
document_date
2024-04-30    1
2023-08-17    1
2025-03-14    1
2018-05-15    1
2021-10-22    1
2024-03-02    1
2019-08-09    1
2022-01-16    1
2025-06-23    1
2020-11-03    1
Name: count, dtype: int64

--- document_type ---
Nombre de catégories : 6
document_type
inventory_explanation    5
security_instruction     5
meeting_record           5
internal_memorandum      5
procurement_note         5
shipment_report          5
Name: count, dtype: int64

--- author_name ---
Nombre de catégories : 27
author_name
Soren Kade        4
Adrian Vosmere    1
Dr. Elias Voss    1
Jacob Vale        1
Amara Senn        1
Niko Verran       1
Celene Varro      1
Oskar Nivren      1
Adrienne Solva    1
Tomas Pell        1
Name: count, dtype: int64

--- author_organization ---
Nombre de catégories : 13
author_organization
Meridian BioLogistics                 7
Vale Strategy Collective              3
Northstar Cold Chain Services         3
Nivren Maritime Logistics             2
Solvane Energy Group                  2
Whitehaven Strategic Holdings         2
Valenne Industrial Futures Council    2
Ardena Capital Union                  2
Helix Legal and Compliance            2
Earth Ledger Project                  2
Name: count, dtype: int64

--- recipient_text ---
Nombre de catégories : 2
recipient_text
Operations, finance, and compliance           27
Restricted operations and compliance group     3
Name: count, dtype: int64

--- subject_line ---
Nombre de catégories : 30
subject_line
April Biological-Unit Reconciliation           1
Secure Delivery Record-Handling Instruction    1
Restricted CHAMELEO Governance Review          1
Internal Operations Memorandum 56              1
  Internal  Operations  Memorandum  57         1
Internal Operations Memorandum 58              1
Internal Operations Memorandum 59              1
Internal Operations Memorandum 60              1
Procurement Justification 61                   1
Procurement Justification 62                   1
Name: count, dtype: int64

--- text ---
Nombre de catégories : 30
text
SUBJECT\nUnresolved biological-unit imbalance following April inventory reconciliation.\n\nCONTEXT\nThe monthly reconciliation reviewed receipts, declared internal use, documented waste, adjustments, and outbound records for the controlled biological-sample category. Adjustment ADJ-2022-00088 was included in the review. Unit conversions were checked against the current item master.\n\nFINDINGS\nThe opening balance and posted receipts reconcile with the warehouse ledger. Declared internal use and waste are supported by signed records. The outbound register accounts for the listed shipments, but the calculated closing balance remains above the physical count. A recount by a second controller produced the same result. No temperature excursion or damaged-container report explains the difference.\n\nThe discrepancy is concentrated in sealed biological units handled under restricted authorization. Similar differences have occurred in earlier periods, although their direction and size vary. Ordinary causes such as delayed posting, split batches, unit conversion, and transfer between storage locations remain under review.\n\nACTION\nMaintain the adjustment as provisional, suspend automatic closure of the period, and obtain the secure dispatch register for comparison. This memorandum establishes a material sink in the accounting sequence; it does not identify a destination, user, or purpose.                                                                                                                                                                                                                                                                     1
SCOPE\nThis instruction applies to staff handling secure delivery records associated with shipment SHP-2022-00011 and related restricted consignments.\n\nCONTROL REQUIREMENTS\nRecords marked CHAMELEO are to be routed through the designated compliance queue. Staff must verify the receiving facility code, named authorization class, seal number, and temperature-control record before release. Copies are not to be attached to ordinary customer correspondence. Route changes require approval from the security manager and the duty compliance officer.\n\nRESPONSIBILITIES\nOperations staff retain the ordinary shipment record. Security staff retain the sealed routing appendix. Warehouse staff record only the declared cargo category and quantity in the standard inventory system. Any mismatch between the standard record and the restricted appendix must be escalated rather than corrected locally.\n\nESCALATION\nContact the secure-delivery desk for missing signatures, unexplained destination changes, or requests to bypass the receiving scan. The code identifies a handling and governance procedure. This instruction does not explain the programme's wider purpose, the ownership of the designation, or the final use of any cargo.                                                                                                                                                                                                                                                                                                                                                                                                                                                     1
MEETING RECORD — RESTRICTED GOVERNANCE REVIEW\n\nAttendees included the executive chair, the secure-delivery manager, clinical programme counsel, and the records secretary.\n\nAGENDA\n1. Authority for CHAMELEO routing.\n2. Relationship between programme designation and executive approvals.\n3. Separation of ordinary corporate records from restricted appendices.\n\nDISCUSSION\nThe chair confirmed that Unwabu is the designation used in the restricted governance schedule for the authority approving CHAMELEO exceptions. The same schedule assigns final escalation to the Meridian executive office. Participants agreed that ordinary employees should see only shipment, inventory, and compliance fields needed for their roles. The secretary noted that earlier instructions treated CHAMELEO as a handling code, while the governance schedule links it to a named authority.\n\nDECISIONS\nThe secure-delivery manager will maintain the restricted appendix. Compliance will retain a cross-reference between the designation, executive approvals, and affected routes. No change will be made to public corporate filings.\n\nLIMITS\nThis record establishes an Unwabu–CHAMELEO–Meridian authority bridge. The meeting did not review other networks, biological questions, ecological material, or destination records.\n\nThe chair instructed staff not to alter existing operational records retrospectively. Any reconciliation should be recorded as a new governance note with a visible date and responsible role. The meeting did not review ecological evidence or clinical files, and participants were reminded that their authority was limited to routing and programme governance.    1
SUBJECT\nOperational review of cold-chain reconciliation.\n\nCONTEXT\nRecords SHP-2020-00019 were checked against the ordinary approval path.\n\nFACTS\nDates, quantities, and facility codes are consistent. One document arrived after the accounting cut-off and requires a visible late-posting note.\n\nACTION\nThe process owner will attach the source record and close the review after second-person approval.\n\nThe operational issue concerns cold-chain reconciliation and was reviewed through the ordinary procurement, shipment, and inventory records.\n\nQuantities, units, authorizations, facility codes, and dates were compared before any adjustment was proposed.\n\nThe memo records a practical decision and named owner without inferring an undisclosed purpose.\n\nOrdinary causes include posting delay, split batches, transfer timing, supplier substitution, and documentation lag.\n\nRestricted handling is treated as a control category rather than evidence of a hidden programme.                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          1
SUBJECT\nOperational review of supplier onboarding.\n\nCONTEXT\nRecords ADJ-2019-00052 were checked against the ordinary approval path.\n\nFACTS\nDates, quantities, and facility codes are consistent. One document arrived after the accounting cut-off and requires a visible late-posting note.\n\nACTION\nThe process owner will attach the source record and close the review after second-person approval.\n\nThe operational issue concerns supplier onboarding and was reviewed through the ordinary procurement, shipment, and inventory records.\n\nQuantities, units, authorizations, facility codes, and dates were compared before any adjustment was proposed.\n\nThe memo records a practical decision and named owner without inferring an undisclosed purpose.\n\nOrdinary causes include posting delay, split batches, transfer timing, supplier substitution, and documentation lag.\n\nRestricted handling is treated as a control category rather than evidence of a hidden programme.                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      1
SUBJECT\nOperational review of shipment exception.\n\nCONTEXT\nRecords  were checked against the ordinary approval path.\n\nFACTS\nDates, quantities, and facility codes are consistent. One document arrived after the accounting cut-off and requires a visible late-posting note.\n\nACTION\nThe process owner will attach the source record and close the review after second-person approval.\n\nThe operational issue concerns shipment exception and was reviewed through the ordinary procurement, shipment, and inventory records.\n\nQuantities, units, authorizations, facility codes, and dates were compared before any adjustment was proposed.\n\nThe memo records a practical decision and named owner without inferring an undisclosed purpose.\n\nOrdinary causes include posting delay, split batches, transfer timing, supplier substitution, and documentation lag.\n\nRestricted handling is treated as a control category rather than evidence of a hidden programme.                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      1
SUBJECT\nOperational review of inventory close.\n\nCONTEXT\nRecords  were checked against the ordinary approval path.\n\nFACTS\nDates, quantities, and facility codes are consistent. One document arrived after the accounting cut-off and requires a visible late-posting note.\n\nACTION\nThe process owner will attach the source record and close the review after second-person approval.\n\nThe operational issue concerns inventory close and was reviewed through the ordinary procurement, shipment, and inventory records.\n\nQuantities, units, authorizations, facility codes, and dates were compared before any adjustment was proposed.\n\nThe memo records a practical decision and named owner without inferring an undisclosed purpose.\n\nOrdinary causes include posting delay, split batches, transfer timing, supplier substitution, and documentation lag.\n\nRestricted handling is treated as a control category rather than evidence of a hidden programme.                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            1
SUBJECT\nOperational review of secure records handling.\n\nCONTEXT\nRecords PO-2022-00044 were checked against the ordinary approval path.\n\nFACTS\nDates, quantities, and facility codes are consistent. One document arrived after the accounting cut-off and requires a visible late-posting note.\n\nACTION\nThe process owner will attach the source record and close the review after second-person approval.\n\nThe operational issue concerns secure records handling and was reviewed through the ordinary procurement, shipment, and inventory records.\n\nQuantities, units, authorizations, facility codes, and dates were compared before any adjustment was proposed.\n\nThe memo records a practical decision and named owner without inferring an undisclosed purpose.\n\nOrdinary causes include posting delay, split batches, transfer timing, supplier substitution, and documentation lag.\n\nRestricted handling is treated as a control category rather than evidence of a hidden programme.                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               1
REQUEST\nProcurement request  for standard programme supplies.\n\nJUSTIFICATION\nThe requested quantity reflects scheduled use, safety stock, and expected delivery time.\n\nSUPPLIER AND QUANTITY\nThe approved supplier and unit match the item master. No substitution is authorized without written review.\n\nAUTHORIZATION\nProceed within the declared cost center and ordinary approval threshold.\n\nThe operational issue concerns procurement authorization and was reviewed through the ordinary procurement, shipment, and inventory records.\n\nQuantities, units, authorizations, facility codes, and dates were compared before any adjustment was proposed.\n\nThe memo records a practical decision and named owner without inferring an undisclosed purpose.\n\nOrdinary causes include posting delay, split batches, transfer timing, supplier substitution, and documentation lag.                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           1
REQUEST\nProcurement request  for standard programme supplies.\n\nJUSTIFICATION\nThe requested quantity reflects scheduled use, safety stock, and expected delivery time.\n\nSUPPLIER AND QUANTITY\nThe approved supplier and unit match the item master. No substitution is authorized without written review.\n\nAUTHORIZATION\nProceed within the declared cost center and ordinary approval threshold.\n\nThe operational issue concerns warehouse access and was reviewed through the ordinary procurement, shipment, and inventory records.\n\nQuantities, units, authorizations, facility codes, and dates were compared before any adjustment was proposed.\n\nThe memo records a practical decision and named owner without inferring an undisclosed purpose.\n\nOrdinary causes include posting delay, split batches, transfer timing, supplier substitution, and documentation lag.                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    1
Name: count, dtype: int64

--- related_purchase_order ---
Nombre de catégories : 5
related_purchase_order
PO-2022-00044    1
PO-2023-00038    1
PO-2024-00016    1
PO-2025-00039    1
PO-2017-00006    1
Name: count, dtype: int64

--- related_shipment_number ---
Nombre de catégories : 8
related_shipment_number
SHP-2022-00011    1
SHP-2023-00035    1
SHP-2020-00019    1
SHP-2022-00025    1
SHP-2023-00059    1
SHP-2025-00034    1
SHP-2018-00041    1
SHP-2020-00044    1
Name: count, dtype: int64

--- related_case_number ---
Nombre de catégories : 8
related_case_number
REG-2024-0036    2
REG-2022-0022    2
ACC-2019-0005    1
ACC-2018-0024    1
ACC-2023-0047    1
REG-2024-0009    1
ACC-2020-0008    1
ACC-2023-0028    1
Name: count, dtype: int64

--- visibility_level ---
Nombre de catégories : 3
visibility_level
restricted      11
confidential    10
internal         9
Name: count, dtype: int64

In [162]:
# def extract_document_type(text):
#     text = str(text).strip().upper()

#     if text.startswith("SUBJECT"):
#         return "SUBJECT"
#     elif text.startswith("SCOPE"):
#         return "SCOPE"
#     elif text.startswith("MEETING RECORD"):
#         return "MEETING"
#     elif text.startswith("REQUEST"):
#         return "REQUEST"
#     elif text.startswith("ROUTE"):
#         return "ROUTE"
#     elif text.startswith("PERIOD"):
#         return "PERIOD"
#     else:
#         return "OTHER"


# df_pr["document_type"] = df["text"].apply(extract_document_type)
# df_pr = df_pr.drop('text', axis=1)
df_pr.to_csv("data/public_records/institutional_memos.csv", index=False)

licensed_facilities.csv

In [163]:
df_lf = pd.read_csv("data/public_records/licensed_facilities.csv") #à finir quand on saura faire les textes

on enleve cette tab car elle est vide elle ne contient rien

In [150]:
df_lf = df_lf.drop('license_end', axis=1)
df_lf = df_lf.drop('facility_status', axis=1)

In [151]:
print(df_lf.head)

<bound method NDFrame.head of   facility_license_number                       facility_name  \
0             FAC-VLN-101    Asterion Central Clinical Campus
1             FAC-AVL-201   Asterion Avelora Executive Clinic
2             FAC-AVL-301  Threshold Earth Avelora Laboratory

     facility_category operating_organization_registration  \
0    research_hospital                       REG-VLN-01002
1       private_clinic                       REG-VLN-01002
2  research_laboratory                       REG-AVL-01007

                                      street_address              region  \
0  Asterion Central Clinical Campus, Valenne Cent...    Valenne Republic
1  Asterion Avelora Executive Clinic, Eastern Ave...  Avelora Federation
2  Threshold Earth Avelora Laboratory, Eastern Av...  Avelora Federation

   latitude  longitude license_start  \
0     47.20       7.51    2001-02-01
1      7.35     101.62    2008-05-15
2      7.50     101.75    2012-01-18

                                   declared_services
0  preventive medicine; cardiac assessment; clini...
1  executive health; specialist follow-up; outpat...
2  environmental health research; non-invasive hu...  >

licensed_professionals.csv

In [152]:
df_lp = pd.read_csv("data/public_records/licensed_professionals.csv")

In [153]:
# Valeurs manquantes
# print(df_lp.isna().sum())
# print(len(df_lp))

# Nombre de valeurs uniques
print(df_lp.nunique())

license_number              53
professional_name           53
profession                   5
specialty                   16
license_issue_date          40
license_expiry_date          0
license_status               1
primary_facility_license     3
registered_region            5
disciplinary_status          2
dtype: int64

In [154]:
print(df_lp.columns)

Index(['license_number', 'professional_name', 'profession', 'specialty',
       'license_issue_date', 'license_expiry_date', 'license_status',
       'primary_facility_license', 'registered_region', 'disciplinary_status'],
      dtype='object')

on a décidé de les supprimer car ils ont tous la même valeur ou sont vides

In [155]:
df_lp = df_lp.drop('license_status', axis=1)
df_lp = df_lp.drop('license_expiry_date', axis=1)

In [156]:
df_lp['license_issue_date'] = pd.to_datetime(df_lp['license_issue_date'], format='%Y-%m-%d', errors='coerce')
df_lp[df_lp['license_issue_date'].isna()]
df_lp.loc[26, 'license_issue_date'] = pd.to_datetime('1994-07-01', format='%Y-%m-%d')

In [157]:
print(df_lp.iloc[26])

license_number                                LIC-TMB-ADM-1027
professional_name                                  Doran Maren
profession                  public administration professional
specialty                             programme administration
license_issue_date                         1994-07-01 00:00:00
primary_facility_license                                   NaN
registered_region                                     Tembaran
disciplinary_status                                       none
Name: 26, dtype: object