<a href="https://colab.research.google.com/github/Sheik-info/20262027-UE-DataMining-Project/blob/main/logistics.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# UE Data Mining - Projet

**Logistics**

In [49]:
# TODO
!git clone https://github.com/Sheik-info/20262027-UE-DataMining-Project.git
%cd 20262027-UE-DataMining-Project

Cloning into '20262027-UE-DataMining-Project'...
remote: Enumerating objects: 213, done.
remote: Counting objects: 100% (36/36), done.
remote: Compressing objects: 100% (29/29), done.
remote: Total 213 (delta 20), reused 7 (delta 7), pack-reused 177 (from 1)
Receiving objects: 100% (213/213), 1.84 MiB | 8.01 MiB/s, done.
Resolving deltas: 100% (98/98), done.
/content/20262027-UE-DataMining-Project/20262027-UE-DataMining-Project/20262027-UE-DataMining-Project

In [50]:
!git pull

Already up to date.

On explore ici les jeux de données du dossier `data/logistics/` :
- `erp_facilities.csv` : les entrepôts / sites de l'entreprise
- `erp_business_partners.csv` : les partenaires (clients, fournisseurs, transporteurs...)
- `inventory_month_end.csv` : les stocks en fin de mois par site
- `inventory_adjustments.csv` : les ajustements manuels de stock
- `goods_receipts.csv` : les réceptions de marchandises
- `shipments.csv` : les expéditions
- `purchase_order_lines.csv` : les lignes de commandes d'achat

On commence, comme pour les autres parties, par un premier chargement et une exploration rapide avant de nettoyer quoi que ce soit.

\ 1. Chargement et première exploration
---

In [51]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import os
os.listdir("data/logistics")

['shipments.csv',
 'erp_business_partners.csv',
 'purchase_order_lines.csv',
 'goods_receipts.csv',
 'erp_facilities.csv',
 'inventory_month_end.csv',
 'inventory_adjustments.csv']

Avant de charger les fichiers, on regarde rapidement leurs dimensions et leurs colonnes.
Cela permet de vérifier la structure des données.

In [52]:
# Je regarde rapidement les fichiers avant de commencer
for fichier in os.listdir("data/logistics"):
    df = pd.read_csv("data/logistics/" + fichier)

    print("\n==============================")
    print(fichier)
    print("Dimensions :", df.shape)
    print("Colonnes :", list(df.columns))

==============================
shipments.csv
Dimensions : (452, 16)
Colonnes : ['shipment_number', 'shipment_leg', 'dispatch_time', 'arrival_time', 'sender_partner_code', 'receiver_partner_code', 'origin_facility_code', 'destination_facility_code', 'carrier_partner_code', 'item_category', 'declared_quantity', 'declared_unit', 'temperature_control_class', 'authorization_class', 'declared_purpose', 'shipment_status']

==============================
erp_business_partners.csv
Dimensions : (80, 11)
Colonnes : ['partner_code', 'partner_name', 'partner_role', 'external_registration_number', 'billing_region', 'shipping_region', 'default_currency', 'payment_terms', 'partner_status', 'risk_class', 'onboarding_date']

==============================
purchase_order_lines.csv
Dimensions : (651, 16)
Colonnes : ['purchase_order_number', 'purchase_order_line', 'order_date', 'ordering_facility_code', 'supplier_partner_code', 'item_code', 'item_description', 'item_category', 'ordered_quantity', 'ordered_unit', 'unit_price', 'currency', 'requested_delivery_date', 'authorization_class', 'declared_cost_center', 'order_status']

==============================
goods_receipts.csv
Dimensions : (612, 12)
Colonnes : ['receipt_number', 'purchase_order_number', 'purchase_order_line', 'receipt_date', 'receiving_facility_code', 'supplier_partner_code', 'received_quantity', 'received_unit', 'batch_reference', 'inspection_status', 'storage_location_code', 'receipt_status']

==============================
erp_facilities.csv
Dimensions : (30, 11)
Colonnes : ['facility_code', 'facility_name', 'facility_category', 'operating_partner_code', 'street_address', 'region', 'latitude', 'longitude', 'opening_date', 'facility_status', 'storage_capabilities']

==============================
inventory_month_end.csv
Dimensions : (502, 11)
Colonnes : ['facility_code', 'reporting_month', 'item_category', 'opening_stock', 'received_quantity', 'outgoing_quantity', 'documented_internal_use', 'documented_waste', 'closing_stock', 'unit', 'inventory_status']

==============================
inventory_adjustments.csv
Dimensions : (140, 11)
Colonnes : ['adjustment_number', 'facility_code', 'adjustment_date', 'item_category', 'adjustment_quantity', 'unit', 'adjustment_reason', 'approved_by_role', 'related_receipt_number', 'related_shipment_number', 'adjustment_status']

Les 7 fichiers sont chargés séparément afin de faciliter leur manipulation et leur analyse.

In [53]:
df_fac = pd.read_csv("data/logistics/erp_facilities.csv")
df_bp = pd.read_csv("data/logistics/erp_business_partners.csv")
df_invm = pd.read_csv("data/logistics/inventory_month_end.csv")
df_inva = pd.read_csv("data/logistics/inventory_adjustments.csv")
df_rcv = pd.read_csv("data/logistics/goods_receipts.csv")
df_shp = pd.read_csv("data/logistics/shipments.csv")
df_po = pd.read_csv("data/logistics/purchase_order_lines.csv")

In [54]:
dfs = {
    "facilities": df_fac,
    "business_partners": df_bp,
    "inventory_month_end": df_invm,
    "inventory_adjustments": df_inva,
    "goods_receipts": df_rcv,
    "shipments": df_shp,
    "purchase_order_lines": df_po
}

In [55]:
df_fac.head()

,facility_code,facility_name,facility_category,operating_partner_code,street_address,region,latitude,longitude,opening_date,facility_status,storage_capabilities
0,FCL-1011,Meridian Valenne Headquarters,office,BP-30078,"Meridian Valenne Headquarters, Valenne Central...",Valenne Central District,47.24,7.58,2006-01-01,active,ambient
1,FCL-1024,Meridian Kintara Biological Aggregation Facility,warehouse,BP-30078,Meridian Kintara Biological Aggregation Facili...,Kintara Karst Cluster,4.74,112.28,1997-01-01,active,ambient;secure_cage;2-8C;frozen
2,FCL-1019,Meridian Avelora Transfer Annex,transfer_hub,BP-30078,"Meridian Avelora Transfer Annex, Eastern Avelo...",Eastern Avelora Agricultural Cluster,7.46,101.91,2003-01-01,active,ambient;secure_cage;2-8C;frozen
3,FCL-1020,Meridian Tembara Coastal Hub,transfer_hub,BP-30078,"Meridian Tembara Coastal Hub, Tembara Coastal ...",Tembara Coastal Cluster,2.20,104.55,2010-01-01,active,ambient;secure_cage;2-8C;frozen
4,FCL-1016,Northstar Tembara Cold-Chain Hub,warehouse,BP-30047,"Northstar Tembara Cold-Chain Hub, Tembara Coas...",Tembara Coastal Cluster,2.23,104.58,2008-01-01,active,ambient;secure_cage;2-8C;frozen

Un aperçu des premières lignes est affiché afin de vérifier la structure et le contenu des données.

In [56]:
df_po.head()

,purchase_order_number,purchase_order_line,order_date,ordering_facility_code,supplier_partner_code,item_code,item_description,item_category,ordered_quantity,ordered_unit,unit_price,currency,requested_delivery_date,authorization_class,declared_cost_center,order_status
0,PO-2014-00001,1,2014-06-24,FCL-1007,BP-30078,ITM-MED-001,General clinical consumable case,medical_consumables,73,case,157.85,VLN,2014-07-08,restricted,Clinical Programmes,completed
1,PO-2015-00001,1,2015-01-22,FCL-1010,BP-30068,ITM-TRN-001,Regional refrigerated transport service,transport_service,1,service,3482.27,VLN,2015-02-01,ordinary,Clinical Services,completed
2,PO-2015-00002,1,2015-01-29,FCL-1030,BP-30066,ITM-COM-001,Secure communication service,communication_service,1,service,1292.19,KRN,2015-02-26,ordinary,General Operations,completed
3,PO-2015-00003,1,2015-02-10,FCL-1010,BP-30080,ITM-LAB-002,Sample preparation material pack,laboratory_material,3,pack,458.67,VLN,2015-03-02,expedited,Clinical Services,completed
4,PO-2015-00004,1,2015-02-12,FCL-1022,BP-30021,ITM-GRA-001,Programme grant transfer,grant,1,grant,26933.28,KRN,2015-02-21,ordinary,Facilities,completed

Les types des colonnes sont vérifiés afin de repérer les données qui ne sont pas dans le format attendu.

In [57]:
for nom, df in dfs.items():
    print("\n=======================")
    print(nom)
    print(df.dtypes)

=======================
facilities
facility_code              object
facility_name              object
facility_category          object
operating_partner_code     object
street_address             object
region                     object
latitude                  float64
longitude                 float64
opening_date               object
facility_status            object
storage_capabilities       object
dtype: object

=======================
business_partners
partner_code                    object
partner_name                    object
partner_role                    object
external_registration_number    object
billing_region                  object
shipping_region                 object
default_currency                object
payment_terms                   object
partner_status                  object
risk_class                      object
onboarding_date                 object
dtype: object

=======================
inventory_month_end
facility_code               object
reporting_month             object
item_category               object
opening_stock               object
received_quantity           object
outgoing_quantity           object
documented_internal_use    float64
documented_waste            object
closing_stock               object
unit                        object
inventory_status            object
dtype: object

=======================
inventory_adjustments
adjustment_number          object
facility_code              object
adjustment_date            object
item_category              object
adjustment_quantity        object
unit                       object
adjustment_reason          object
approved_by_role           object
related_receipt_number     object
related_shipment_number    object
adjustment_status          object
dtype: object

=======================
goods_receipts
receipt_number             object
purchase_order_number      object
purchase_order_line         int64
receipt_date               object
receiving_facility_code    object
supplier_partner_code      object
received_quantity          object
received_unit              object
batch_reference            object
inspection_status          object
storage_location_code      object
receipt_status             object
dtype: object

=======================
shipments
shipment_number              object
shipment_leg                  int64
dispatch_time                object
arrival_time                 object
sender_partner_code          object
receiver_partner_code        object
origin_facility_code         object
destination_facility_code    object
carrier_partner_code         object
item_category                object
declared_quantity             int64
declared_unit                object
temperature_control_class    object
authorization_class          object
declared_purpose             object
shipment_status              object
dtype: object

=======================
purchase_order_lines
purchase_order_number      object
purchase_order_line         int64
order_date                 object
ordering_facility_code     object
supplier_partner_code      object
item_code                  object
item_description           object
item_category              object
ordered_quantity           object
ordered_unit               object
unit_price                 object
currency                   object
requested_delivery_date    object
authorization_class        object
declared_cost_center       object
order_status               object
dtype: object

In [58]:
for nom, df in dfs.items():
    print("\n---", nom, "---")

    for colonne in df.columns:
        nb = df[colonne].isna().sum()
        if nb > 0:
            print(colonne, ":", nb)

--- facilities ---
storage_capabilities : 1

--- business_partners ---
external_registration_number : 14
billing_region : 1

--- inventory_month_end ---

--- inventory_adjustments ---
approved_by_role : 1
related_receipt_number : 117
related_shipment_number : 103

--- goods_receipts ---
inspection_status : 4

--- shipments ---
arrival_time : 17

--- purchase_order_lines ---
declared_cost_center : 3

Certaines colonnes contenant des quantités et des prix sont actuellement au format `object`. Elles devront être converties dans un format numérique avant de poursuivre l'analyse.

 2. Nettoyage

---

#### 2.1 Lignes dupliquées

La présence de lignes dupliquées est vérifiée dans chaque fichier.

In [59]:
for nom, df in dfs.items():
    print(nom, ":", df.duplicated().sum(), "doublon(s)")

facilities : 0 doublon(s)
business_partners : 0 doublon(s)
inventory_month_end : 2 doublon(s)
inventory_adjustments : 0 doublon(s)
goods_receipts : 2 doublon(s)
shipments : 2 doublon(s)
purchase_order_lines : 1 doublon(s)

##### Suppression des doublons

In [60]:
df_invm = df_invm.drop_duplicates().reset_index(drop=True)
df_rcv = df_rcv.drop_duplicates().reset_index(drop=True)
df_shp = df_shp.drop_duplicates().reset_index(drop=True)
df_po = df_po.drop_duplicates().reset_index(drop=True)

dfs["inventory_month_end"] = df_invm
dfs["goods_receipts"] = df_rcv
dfs["shipments"] = df_shp
dfs["purchase_order_lines"] = df_po

for nom, df in dfs.items():
    print(nom, ":", df.shape[0], "lignes")

facilities : 30 lignes
business_partners : 80 lignes
inventory_month_end : 500 lignes
inventory_adjustments : 140 lignes
goods_receipts : 610 lignes
shipments : 450 lignes
purchase_order_lines : 650 lignes

##### 2.2 Colonnes constantes

Les colonnes qui contiennent une seule valeur, ou qui sont entièrement vides, sont repérées. Elles n'apportent pas de variation pour l'analyse et peuvent donc être supprimées.

In [61]:
for nom, df in dfs.items():
    cols_constantes = [c for c in df.columns if df[c].nunique(dropna=False) <= 1]

    if cols_constantes:
        print(nom, ":", cols_constantes)

facilities : ['facility_status']
goods_receipts : ['purchase_order_line']
shipments : ['shipment_leg']
purchase_order_lines : ['purchase_order_line']

Suppression des colonnes qui ne varient pas

In [62]:
df_fac = df_fac.drop(columns=["facility_status"])

df_rcv = df_rcv.drop(columns=["purchase_order_line"])
df_po = df_po.drop(columns=["purchase_order_line"])

df_shp = df_shp.drop(columns=["shipment_leg"])

dfs["facilities"] = df_fac
dfs["goods_receipts"] = df_rcv
dfs["purchase_order_lines"] = df_po
dfs["shipments"] = df_shp

#### 2.3 Nettoyage des colonnes numériques — inventory_month_end

Les colonnes `opening_stock`, `received_quantity`, `outgoing_quantity`, `documented_waste` et `closing_stock` sont actuellement de type `object` alors qu'elles devraient être numériques. Deux problèmes de format sont en cause :

- certaines valeurs utilisent une virgule comme séparateur décimal (ex : `"5,42"`) au lieu d'un point ;
- certaines valeurs contiennent l'unité collée au nombre (ex : `"14.55 sealed_lot"`). Cette unité est redondante avec la colonne `unit` déjà présente, elle peut donc être retirée sans perte d'information.

Une fonction de nettoyage est appliquée à ces colonnes.

In [63]:
import re

def nettoyer_colonne_numerique(serie):
    s = serie.astype(str).str.strip()
    s = s.str.replace(',', '.', regex=False)
    s = s.str.extract(r'(-?\d+\.?\d*)')[0]
    return pd.to_numeric(s, errors='coerce')

colonnes_a_nettoyer = ['opening_stock', 'received_quantity', 'outgoing_quantity',
                        'documented_waste', 'closing_stock']

for col in colonnes_a_nettoyer:
    df_invm[col] = nettoyer_colonne_numerique(df_invm[col])

df_invm.dtypes

facility_code               object
reporting_month             object
item_category               object
opening_stock              float64
received_quantity          float64
outgoing_quantity          float64
documented_internal_use    float64
documented_waste           float64
closing_stock              float64
unit                        object
inventory_status            object
dtype: object

La colonne `inventory_status` présente aussi une incohérence de casse (`"closed"` / `"CLOSED"`, `"provisional"` / `"PROVISIONAL"`). Elle est uniformisée en minuscules.

In [64]:
df_invm['inventory_status'] = df_invm['inventory_status'].str.lower()
df_invm['inventory_status'].value_counts()

inventory_status
closed         444
provisional     38
revised         18
Name: count, dtype: int64

##### Vérification de cohérence comptable

Le stock de fin de mois (`closing_stock`) devrait théoriquement correspondre à :
`opening_stock + received_quantity − outgoing_quantity − documented_internal_use − documented_waste`.

Un écart entre valeur déclarée et valeur recalculée est ajouté comme nouvelle colonne, afin d'être analysé plus tard plutôt que d'être corrigé arbitrairement.

In [65]:
dfs["inventory_month_end"] = df_invm

In [66]:
df_invm.dtypes

facility_code               object
reporting_month             object
item_category               object
opening_stock              float64
received_quantity          float64
outgoing_quantity          float64
documented_internal_use    float64
documented_waste           float64
closing_stock              float64
unit                        object
inventory_status            object
dtype: object

In [67]:
df_invm.head()

,facility_code,reporting_month,item_category,opening_stock,received_quantity,outgoing_quantity,documented_internal_use,documented_waste,closing_stock,unit,inventory_status
0,FCL-1024,2018-02-01,biological_sample,14.55,5.46,0.00,0.49,0.22,16.24,sealed_lot,closed
1,FCL-1024,2018-03-01,biological_sample,16.24,5.00,0.00,1.94,0.65,0.55,sealed_lot,closed
2,FCL-1024,2018-05-01,biological_sample,0.55,0.00,0.00,0.00,0.36,0.17,sealed_lot,closed
3,FCL-1024,2019-01-01,biological_sample,0.17,0.00,1.37,0.00,0.02,0.00,sealed_lot,provisional
4,FCL-1024,2019-08-01,biological_sample,0.00,3.12,8.80,0.00,0.08,0.00,sealed_lot,closed

#### 2.4 Nettoyage des colonnes numériques — goods_receipts

La colonne `received_quantity` présente les mêmes problèmes de format que `inventory_month_end` : virgule décimale et unité collée à la valeur (redondante avec `received_unit`). La même fonction de nettoyage est réutilisée.

In [68]:
df_rcv['received_quantity'] = nettoyer_colonne_numerique(df_rcv['received_quantity'])
df_rcv['received_quantity'].describe()

count    610.000000
mean      20.591770
std       22.947117
min        0.780000
25%        1.000000
50%       13.000000
75%       29.000000
max       90.000000
Name: received_quantity, dtype: float64

La colonne `receipt_status` présente une incohérence de casse (`"posted"` / `"POSTED"`), uniformisée en minuscules.

In [69]:
df_rcv['receipt_status'] = df_rcv['receipt_status'].str.lower()
df_rcv['receipt_status'].value_counts()

receipt_status
posted          576
quality_hold     34
Name: count, dtype: int64

4 lignes présentent une valeur manquante pour `inspection_status`, toutes avec un `receipt_status` égal à `"posted"`. Plutôt que de supposer une valeur, ces cas sont rendus explicites avec la catégorie `"non_renseigne"`.

In [70]:
df_rcv['inspection_status'] = df_rcv['inspection_status'].fillna('non_renseigne')
df_rcv['inspection_status'].value_counts()

inspection_status
accepted         505
conditional       67
held              34
non_renseigne      4
Name: count, dtype: int64

In [71]:
dfs["goods_receipts"] = df_rcv

In [72]:
df_rcv.dtypes

receipt_number              object
purchase_order_number       object
receipt_date                object
receiving_facility_code     object
supplier_partner_code       object
received_quantity          float64
received_unit               object
batch_reference             object
inspection_status           object
storage_location_code       object
receipt_status              object
dtype: object

In [73]:
df_rcv.head()

,receipt_number,purchase_order_number,receipt_date,receiving_facility_code,supplier_partner_code,received_quantity,received_unit,batch_reference,inspection_status,storage_location_code,receipt_status
0,RCV-2014-00001,PO-2014-00001,2014-07-08,FCL-1007,BP-30078,73.0,case,B-2014-44545,held,BIN-35,quality_hold
1,RCV-2015-00002,PO-2015-00001,2015-02-02,FCL-1010,BP-30068,0.9,service,B-2015-58495,accepted,BIN-36,posted
2,RCV-2015-00003,PO-2015-00002,2015-02-28,FCL-1030,BP-30066,1.0,service,B-2015-48474,held,BIN-17,quality_hold
3,RCV-2015-00004,PO-2015-00003,2015-03-02,FCL-1010,BP-30080,3.0,pack,B-2015-71913,accepted,BIN-16,posted
4,RCV-2015-00005,PO-2015-00004,2015-02-21,FCL-1022,BP-30021,1.0,grant,B-2015-31154,accepted,BIN-42,posted

#### 2.5 Nettoyage des colonnes numériques — purchase_order_lines

Les colonnes `ordered_quantity` (unité collée) et `unit_price` (virgule décimale) présentent les mêmes problèmes de format que les fichiers précédents.

In [74]:
df_po['ordered_quantity'] = nettoyer_colonne_numerique(df_po['ordered_quantity'])
df_po['unit_price'] = nettoyer_colonne_numerique(df_po['unit_price'])
df_po[['ordered_quantity', 'unit_price']].describe()

       ordered_quantity    unit_price
count        650.000000    650.000000
mean          20.964615   3844.168754
std           23.136234   5701.539177
min            1.000000     83.810000
25%            1.000000    560.435000
50%           14.000000   1600.670000
75%           30.000000   4243.115000
max           90.000000  28663.740000

La colonne `item_category` présente des doublons de casse (ex : `"monitoring_equipment"` / `"MONITORING_EQUIPMENT"`), uniformisés en minuscules.

In [75]:
df_po['item_category'] = df_po['item_category'].str.lower()
df_po['item_category'].value_counts()

item_category
medical_consumables       79
monitoring_equipment      57
cold_storage_equipment    54
agricultural_product      53
protective_equipment      49
laboratory_material       44
biological_sample         42
office_supply             37
transport_service         33
other                     33
refrigeration_service     29
consulting_service        25
agricultural_equipment    23
legal_service             22
research_contract         22
medical_equipment         20
communication_service     17
grant                     11
Name: count, dtype: int64

3 lignes présentent une valeur manquante pour `declared_cost_center`, sans motif apparent. Comme pour `inspection_status`, ces cas sont rendus explicites avec la catégorie `"non_renseigne"` plutôt que de supposer une valeur.

In [76]:
df_po['declared_cost_center'] = df_po['declared_cost_center'].fillna('non_renseigne')
df_po['declared_cost_center'].value_counts()

declared_cost_center
Field Programmes             98
Clinical Services            93
Research Services            90
Agricultural Distribution    87
General Operations           84
Facilities                   81
Cold Chain                   70
Clinical Programmes          26
Field Operations             18
non_renseigne                 3
Name: count, dtype: int64

**Point de vigilance pour l'analyse** : `unit_price` est exprimé dans 5 devises différentes (VLN, AVL, TMB, NDH, KRN). Toute comparaison  de prix entre commandes nécessitera une standardisation (a faire plus tard)

In [77]:
dfs["purchase_order_lines"] = df_po

In [78]:
df_po.head()

,purchase_order_number,order_date,ordering_facility_code,supplier_partner_code,item_code,item_description,item_category,ordered_quantity,ordered_unit,unit_price,currency,requested_delivery_date,authorization_class,declared_cost_center,order_status
0,PO-2014-00001,2014-06-24,FCL-1007,BP-30078,ITM-MED-001,General clinical consumable case,medical_consumables,73,case,157.85,VLN,2014-07-08,restricted,Clinical Programmes,completed
1,PO-2015-00001,2015-01-22,FCL-1010,BP-30068,ITM-TRN-001,Regional refrigerated transport service,transport_service,1,service,3482.27,VLN,2015-02-01,ordinary,Clinical Services,completed
2,PO-2015-00002,2015-01-29,FCL-1030,BP-30066,ITM-COM-001,Secure communication service,communication_service,1,service,1292.19,KRN,2015-02-26,ordinary,General Operations,completed
3,PO-2015-00003,2015-02-10,FCL-1010,BP-30080,ITM-LAB-002,Sample preparation material pack,laboratory_material,3,pack,458.67,VLN,2015-03-02,expedited,Clinical Services,completed
4,PO-2015-00004,2015-02-12,FCL-1022,BP-30021,ITM-GRA-001,Programme grant transfer,grant,1,grant,26933.28,KRN,2015-02-21,ordinary,Facilities,completed

#### 2.6 Nettoyage des colonnes — inventory_adjustments

`adjustment_quantity` présente une unité collée sur une ligne (redondante avec `unit`), retirée avec la même fonction que précédemment.

In [79]:
df_inva['adjustment_quantity'] = nettoyer_colonne_numerique(df_inva['adjustment_quantity'])
df_inva['adjustment_quantity'].describe()

count    140.000000
mean      -0.598857
std        3.995308
min       -7.910000
25%       -3.035000
50%       -1.805000
75%        2.005000
max        7.870000
Name: adjustment_quantity, dtype: float64

`adjustment_reason` présente des doublons de casse, uniformisés en minuscules.

In [80]:
df_inva['adjustment_reason'] = df_inva['adjustment_reason'].str.lower()
df_inva['adjustment_reason'].value_counts()

adjustment_reason
transfer posting correction    24
cycle count correction         23
quality-hold release           21
damaged packaging write-off    16
unit-of-measure review         12
specialist programme issue     11
procedure stock issue          10
late receipt posting            9
controlled-area consumption     9
cycle count reconciliation      5
Name: count, dtype: int64

In [81]:
df_inva['approved_by_role'] = df_inva['approved_by_role'].fillna('non_renseigne')

In [82]:
dfs["inventory_adjustments"] = df_inva

In [83]:
df_inva.head()

,adjustment_number,facility_code,adjustment_date,item_category,adjustment_quantity,unit,adjustment_reason,approved_by_role,related_receipt_number,related_shipment_number,adjustment_status
0,ADJ-2014-00001,FCL-1007,2014-07-18,medical_consumables,-1.58,case,specialist programme issue,clinical stores manager,NaN,NaN,posted
1,ADJ-2015-00002,FCL-1007,2015-09-10,medical_consumables,-2.70,case,specialist programme issue,specialist programme administrator,NaN,NaN,posted
2,ADJ-2015-00003,FCL-1024,2015-10-30,monitoring_equipment,3.68,kit,late receipt posting,warehouse manager,RCV-2022-00361,NaN,posted
3,ADJ-2016-00004,FCL-1007,2016-01-20,biological_sample,6.52,sealed_lot,late receipt posting,finance controller,NaN,NaN,pending_review
4,ADJ-2016-00005,FCL-1010,2016-02-18,medical_consumables,-2.43,case,procedure stock issue,quality manager,NaN,NaN,posted

#### 2.7 Nettoyage — erp_facilities
 Ce fichier ne présente pas de problème de format numérique ni de casse. Seule la colonne storage_capabilities contient une valeur manquante

In [84]:
df_fac['storage_capabilities'] = df_fac['storage_capabilities'].fillna('non_renseigne')
df_fac['storage_capabilities'].value_counts()

storage_capabilities
ambient;secure_cage                9
ambient;secure_cage;2-8C;frozen    8
ambient                            6
2-8C;controlled_access             6
non_renseigne                      1
Name: count, dtype: int64

mise à jour du dic

In [85]:
dfs["facilities"] = df_fac
df_fac.head()

,facility_code,facility_name,facility_category,operating_partner_code,street_address,region,latitude,longitude,opening_date,storage_capabilities
0,FCL-1011,Meridian Valenne Headquarters,office,BP-30078,"Meridian Valenne Headquarters, Valenne Central...",Valenne Central District,47.24,7.58,2006-01-01,ambient
1,FCL-1024,Meridian Kintara Biological Aggregation Facility,warehouse,BP-30078,Meridian Kintara Biological Aggregation Facili...,Kintara Karst Cluster,4.74,112.28,1997-01-01,ambient;secure_cage;2-8C;frozen
2,FCL-1019,Meridian Avelora Transfer Annex,transfer_hub,BP-30078,"Meridian Avelora Transfer Annex, Eastern Avelo...",Eastern Avelora Agricultural Cluster,7.46,101.91,2003-01-01,ambient;secure_cage;2-8C;frozen
3,FCL-1020,Meridian Tembara Coastal Hub,transfer_hub,BP-30078,"Meridian Tembara Coastal Hub, Tembara Coastal ...",Tembara Coastal Cluster,2.20,104.55,2010-01-01,ambient;secure_cage;2-8C;frozen
4,FCL-1016,Northstar Tembara Cold-Chain Hub,warehouse,BP-30047,"Northstar Tembara Cold-Chain Hub, Tembara Coas...",Tembara Coastal Cluster,2.23,104.58,2008-01-01,ambient;secure_cage;2-8C;frozen

###2.8 Nettoyage — erp_business_partners
partner_role présente une incohérence de casse ("Supplier" / "supplier"), comme observé précédemment pour item_category dans purchase_order_lines. Elle est uniformisée en minuscules.

In [86]:
df_bp['partner_role'] = df_bp['partner_role'].str.lower()
df_bp['partner_role'].value_counts()

partner_role
customer             32
service_partner      19
supplier             14
carrier               9
supplier_customer     6
Name: count, dtype: int64

external_registration_number (14 valeurs manquantes) et billing_region (1 valeur manquante) ne présentent pas de motif apparent expliquant leur absence. Ces cas sont rendus explicites avec la catégorie "non_renseigne", dans la continuité de la démarche adoptée pour les autres fichiers

In [87]:
df_bp['external_registration_number'] = df_bp['external_registration_number'].fillna('non_renseigne')
df_bp['billing_region'] = df_bp['billing_region'].fillna('non_renseigne')

Point de vigilance pour l'analyse : la colonne shipping_region mélange deux granularités géographiques différentes (ex : "Valenne Central District" face à "Valenne Republic"). Cette hétérogénéité n'est pas corrigée ici mais devra être prise en compte lors d'agrégations géographiques (à faire lors de l'analyse)

In [88]:
dfs["business_partners"] = df_bp
df_bp.head()

,partner_code,partner_name,partner_role,external_registration_number,billing_region,shipping_region,default_currency,payment_terms,partner_status,risk_class,onboarding_date
0,BP-30001,Marula Cold Store Cooperative,supplier_customer,REG-AVL-20012,Avelora Federation,Eastern Avelora Agricultural Cluster,AVL,NET45,active,review,2001-02-01
1,BP-30002,Blue Heron Monitoring Cooperative,customer,REG-KNT-20037,Kintara Republic,Kintara Karst Cluster,KRN,NET45,active,standard,2012-03-01
2,BP-30003,Orra Technical Services,supplier,REG-AVL-20022,Avelora Federation,Eastern Avelora Agricultural Cluster,AVL,PUBLIC30,active,review,2008-04-01
3,BP-30004,Common Ground Climate Forum,service_partner,REG-VLN-01008,Valenne Republic,Valenne Central District,VLN,PREPAID,active,review,2014-05-01
4,BP-30005,Warden Medical Ventures,service_partner,REG-VLN-01016,Valenne Republic,Valenne Republic,VLN,PREPAID,inactive,standard,2013-06-01

#### 2.8 bis Correction de `partner_name`

En comparant avec les fichiers originaux, on voit qu'un nom de partenaire a encore des espaces en trop (au début, à la fin et en double entre les mots). On réutilise la fonction `nettoyer_espaces` pour le corriger.

In [95]:
# avant : on regarde le nom qui pose probleme
print(df_bp[df_bp['partner_name'].str.contains(r'^\s|\s$|\s{2,}')]['partner_name'].tolist())

# correction
df_bp['partner_name'] = nettoyer_espaces(df_bp['partner_name'])
dfs["business_partners"] = df_bp

# apres : on verifie qu'il n'y en a plus
print(df_bp[df_bp['partner_name'].str.contains(r'^\s|\s$|\s{2,}')].shape[0], "nom(s) avec espaces en trop")

['  Tembara  Customs  Coordination  Unit ']
0 nom(s) avec espaces en trop

###2.9 Nettoyage — shipments

Les doublons et la colonne constante (shipment_leg) ont déjà été traités dans les étapes 2.1 et 2.2. Il reste des incohérences de casse sur deux colonnes catégorielles, un problème d'espaces multiples sur une troisième, et des valeurs manquantes sur arrival_time.

In [89]:
df_shp['temperature_control_class'] = df_shp['temperature_control_class'].str.lower()
df_shp['shipment_status'] = df_shp['shipment_status'].str.lower()

df_shp['temperature_control_class'].value_counts()

temperature_control_class
ambient    343
2-8c       103
frozen       4
Name: count, dtype: int64

In [90]:
df_shp['shipment_status'].value_counts()

shipment_status
delivered     385
delayed        34
in_transit     17
returned       14
Name: count, dtype: int64

declared_purpose présente un problème différent des cas précédents : certaines valeurs contiennent des espaces multiples ou en début de chaîne (ex : " laboratory delivery" au lieu de "laboratory delivery"), ce qui crée artificiellement de fausses catégories distinctes. Une fonction dédiée est utilisée pour normaliser les espaces, sur le même principe que nettoyer_colonne_numerique.

In [91]:
def nettoyer_espaces(serie):
    s = serie.astype(str).str.strip()
    s = s.str.replace(r'\s+', ' ', regex=True)
    return s

df_shp['declared_purpose'] = nettoyer_espaces(df_shp['declared_purpose'])
df_shp['declared_purpose'].value_counts()

declared_purpose
scheduled stock transfer                              74
laboratory delivery                                   72
field programme support                               72
customer distribution                                 64
facility replenishment                                64
agricultural distribution                             60
temperature-controlled clinical programme delivery    26
environmental and wildlife reference materials        18
Name: count, dtype: int64

vérification, pas de modification

In [92]:
df_shp[df_shp['arrival_time'].isna()]['shipment_status'].value_counts()

shipment_status
in_transit    17
Name: count, dtype: int64

mise à jour du dict

In [93]:
dfs["shipments"] = df_shp
df_shp.head()

,shipment_number,dispatch_time,arrival_time,sender_partner_code,receiver_partner_code,origin_facility_code,destination_facility_code,carrier_partner_code,item_category,declared_quantity,declared_unit,temperature_control_class,authorization_class,declared_purpose,shipment_status
0,SHP-2014-00001,2014-07-10T09:00:00,2014-07-11T03:00:00,BP-30078,BP-30021,FCL-1011,FCL-1007,BP-30047,biological_sample,2,sealed_lot,2-8c,expedited,temperature-controlled clinical programme deli...,delivered
1,SHP-2015-00001,2015-01-10T11:00:00,2015-01-13T16:00:00,BP-30035,BP-30033,FCL-1009,FCL-1013,BP-30020,medical_consumables,73,case,2-8c,ordinary,scheduled stock transfer,returned
2,SHP-2015-00002,2015-01-11T06:00:00,2015-01-12T00:00:00,BP-30028,BP-30037,FCL-1020,FCL-1017,BP-30015,office_supply,82,case,ambient,emergency,customer distribution,delivered
3,SHP-2015-00003,2015-02-17T15:00:00,2015-02-19T08:00:00,BP-30056,BP-30078,FCL-1019,FCL-1011,BP-30047,biological_sample,2,sealed_lot,2-8c,restricted,laboratory delivery,delivered
4,SHP-2015-00004,2015-06-10T12:00:00,2015-06-12T09:00:00,BP-30025,BP-30079,FCL-1026,FCL-1022,BP-30025,legal_service,1,service,ambient,ordinary,facility replenishment,delivered

In [94]:
#simple verif
for nom, df in dfs.items():
    print(nom, ":", df.shape)

facilities : (30, 10)
business_partners : (80, 11)
inventory_month_end : (500, 11)
inventory_adjustments : (140, 11)
goods_receipts : (610, 11)
shipments : (450, 15)
purchase_order_lines : (650, 15)

#### 2.10 Conversion des dates

Toutes les colonnes de dates sont encore en texte (`object`). Pour pouvoir calculer des durées, trier dans le temps ou faire des graphiques par mois, il faut les mettre au format date.

En regardant les valeurs, le format est toujours le même (année-mois-jour), mais quelques dates ont un espace au début (ex : `" 2022-03-04"`). On enlève donc les espaces avant de convertir.

Si une date n'arrive pas à être convertie, elle devient `NaT` (équivalent de NaN pour les dates). On vérifie ensuite qu'on n'a pas créé de valeurs manquantes par erreur.

In [96]:
# colonnes de dates a convertir pour chaque fichier
colonnes_dates = {
    "shipments": ["dispatch_time", "arrival_time"],
    "purchase_order_lines": ["order_date", "requested_delivery_date"],
    "goods_receipts": ["receipt_date"],
    "inventory_adjustments": ["adjustment_date"],
    "inventory_month_end": ["reporting_month"],
    "business_partners": ["onboarding_date"],
    "facilities": ["opening_date"]
}

for nom, colonnes in colonnes_dates.items():
    df = dfs[nom]
    for col in colonnes:
        nb_avant = df[col].isna().sum()

        # on enleve les espaces puis on convertit
        df[col] = pd.to_datetime(df[col].astype(str).str.strip(), errors="coerce")

        nb_apres = df[col].isna().sum()
        print(nom, "-", col, ": NaN avant =", nb_avant, "| NaN apres =", nb_apres)

shipments - dispatch_time : NaN avant = 0 | NaN apres = 3
shipments - arrival_time : NaN avant = 17 | NaN apres = 20
purchase_order_lines - order_date : NaN avant = 0 | NaN apres = 3
purchase_order_lines - requested_delivery_date : NaN avant = 0 | NaN apres = 3
goods_receipts - receipt_date : NaN avant = 0 | NaN apres = 5
inventory_adjustments - adjustment_date : NaN avant = 0 | NaN apres = 2
inventory_month_end - reporting_month : NaN avant = 0 | NaN apres = 0
business_partners - onboarding_date : NaN avant = 0 | NaN apres = 1
facilities - opening_date : NaN avant = 0 | NaN apres = 0

In [97]:
# on remet les dataframes a jour
df_shp = dfs["shipments"]
df_po = dfs["purchase_order_lines"]
df_rcv = dfs["goods_receipts"]
df_inva = dfs["inventory_adjustments"]
df_invm = dfs["inventory_month_end"]
df_bp = dfs["business_partners"]
df_fac = dfs["facilities"]

# verification : types et plages de dates
for nom, colonnes in colonnes_dates.items():
    for col in colonnes:
        print(nom, "-", col, ":", dfs[nom][col].dtype,
              "| min =", dfs[nom][col].min(), "| max =", dfs[nom][col].max())

shipments - dispatch_time : datetime64[ns] | min = 2014-07-10 09:00:00 | max = 2025-06-15 13:00:00
shipments - arrival_time : datetime64[ns] | min = 2014-07-11 03:00:00 | max = 2025-06-16 03:00:00
purchase_order_lines - order_date : datetime64[ns] | min = 2014-06-24 00:00:00 | max = 2025-06-23 00:00:00
purchase_order_lines - requested_delivery_date : datetime64[ns] | min = 2014-07-08 00:00:00 | max = 2025-07-22 00:00:00
goods_receipts - receipt_date : datetime64[ns] | min = 2014-07-08 00:00:00 | max = 2025-06-30 00:00:00
inventory_adjustments - adjustment_date : datetime64[ns] | min = 2014-07-18 00:00:00 | max = 2025-06-30 00:00:00
inventory_month_end - reporting_month : datetime64[ns] | min = 2018-02-01 00:00:00 | max = 2025-06-01 00:00:00
business_partners - onboarding_date : datetime64[ns] | min = 1998-04-01 00:00:00 | max = 2019-09-01 00:00:00
facilities - opening_date : datetime64[ns] | min = 1996-01-01 00:00:00 | max = 2015-01-01 00:00:00