<a href="https://colab.research.google.com/github/Sheik-info/20262027-UE-DataMining-Project/blob/main/public_records.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# UE Data Mining - Projet

**Public_records**

In [1]:
# TODO
!git clone https://github.com/Sheik-info/20262027-UE-DataMining-Project.git
%cd 20262027-UE-DataMining-Project

Cloning into '20262027-UE-DataMining-Project'...
remote: Enumerating objects: 282, done.
remote: Counting objects: 100% (90/90), done.
remote: Compressing objects: 100% (82/82), done.
remote: Total 282 (delta 54), reused 11 (delta 8), pack-reused 192 (from 2)
Receiving objects: 100% (282/282), 8.29 MiB | 9.78 MiB/s, done.
Resolving deltas: 100% (138/138), done.
/content/20262027-UE-DataMining-Project

In [2]:
!git pull

Already up to date.

In [3]:
import pandas as pd
import numpy as np

In [4]:
df_pr = pd.read_csv("data/public_records/institutional_memos.csv")  #à finir quand on saura faire les textes
df_lf = pd.read_csv("data/public_records/licensed_facilities.csv") #à finir quand on saura faire les textes
df_lp = pd.read_csv("data/public_records/licensed_professionals.csv")
df_of = pd.read_csv("data/public_records/officer_filings.csv")
df_id = pd.read_csv("data/public_records/public_and_investigative_documents.csv") # à finir quand on saura faire les textes
df_pa = pd.read_csv("data/public_records/public_appointments.csv")
df_re = pd.read_csv("data/public_records/registered_entities.csv")
df_rce = pd.read_csv("data/public_records/regulatory_case_events.csv")
df_sac = pd.read_csv("data/public_records/site_access_case_events.csv")

## institutional_memos.csv

## Nettoyage — `institutional_memos.csv`

Ce fichier contient des notes et mémos institutionnels courts, caractérisés par un champ textuel très dense, complexe et difficile à exploiter directement sous sa forme brute.

**Problèmes identifiés et étapes de traitement :**
1. **Extraction d'informations textuelles :** Analyse de la structure du champ textuel libre pour extraire et catégoriser le type de document (par exemple : `SUBJECT`, `SCOPE`, `MEETING`, `REQUEST`, `ROUTE`, `PERIOD`, ou `OTHER`) afin de structurer l'information.
2. **Identification des colonnes constantes :** Repérage et suppression automatique des colonnes sans pouvoir prédictif ou informatif (celles possédant une seule ou aucune valeur unique).
3. **Gestion des valeurs manquantes :** Évaluation globale du taux de complétude des variables de la table pour éliminer le bruit et conserver uniquement les attributs exploitables.

In [5]:
print(df_pr.head())

# Valeurs manquantes
print(df_pr.isna().sum())

# Nombre de valeurs uniques
print(df_pr.nunique())

  document_id document_date          document_type     author_name  \
0  MEM-510062    2024-04-30  inventory_explanation      Soren Kade
1  MEM-510100    2023-08-17   security_instruction      Soren Kade
2  MEM-510101    2025-03-14         meeting_record      Soren Kade
3  MEM-510128    2018-05-15    internal_memorandum  Adrian Vosmere
4  MEM-510069    2021-10-22    internal_memorandum  Dr. Elias Voss

     author_organization                              recipient_text  \
0  Meridian BioLogistics  Restricted operations and compliance group
1  Meridian BioLogistics  Restricted operations and compliance group
2  Meridian BioLogistics  Restricted operations and compliance group
3    Vosmere Biotechnics         Operations, finance, and compliance
4  Meridian BioLogistics         Operations, finance, and compliance

                                  subject_line  \
0         April Biological-Unit Reconciliation
1  Secure Delivery Record-Handling Instruction
2        Restricted CHAMELEO Governance Review
3            Internal Operations Memorandum 56
4        Internal  Operations  Memorandum  57

                                                text related_purchase_order  \
0  SUBJECT\nUnresolved biological-unit imbalance ...                    NaN
1  SCOPE\nThis instruction applies to staff handl...                    NaN
2  MEETING RECORD — RESTRICTED GOVERNANCE REVIEW\...                    NaN
3  SUBJECT\nOperational review of cold-chain reco...                    NaN
4  SUBJECT\nOperational review of supplier onboar...                    NaN

  related_shipment_number related_case_number visibility_level
0                     NaN                 NaN       restricted
1          SHP-2022-00011                 NaN       restricted
2          SHP-2023-00035                 NaN       restricted
3          SHP-2020-00019                 NaN       restricted
4                     NaN                 NaN         internal
document_id                 0
document_date               0
document_type               0
author_name                 0
author_organization         0
recipient_text              0
subject_line                0
text                        0
related_purchase_order     25
related_shipment_number    22
related_case_number        20
visibility_level            0
dtype: int64
document_id                30
document_date              30
document_type               6
author_name                27
author_organization        13
recipient_text              2
subject_line               30
text                       30
related_purchase_order      5
related_shipment_number     8
related_case_number         8
visibility_level            3
dtype: int64

In [6]:
#pas d'erreur c'est juste qu'on peut le faire qu'une fois
df_pr['document_id'] = df_pr['document_id'].str.replace("MEM-", "", regex=False).astype(int)
print(df_pr.head())

   document_id document_date          document_type     author_name  \
0       510062    2024-04-30  inventory_explanation      Soren Kade
1       510100    2023-08-17   security_instruction      Soren Kade
2       510101    2025-03-14         meeting_record      Soren Kade
3       510128    2018-05-15    internal_memorandum  Adrian Vosmere
4       510069    2021-10-22    internal_memorandum  Dr. Elias Voss

     author_organization                              recipient_text  \
0  Meridian BioLogistics  Restricted operations and compliance group
1  Meridian BioLogistics  Restricted operations and compliance group
2  Meridian BioLogistics  Restricted operations and compliance group
3    Vosmere Biotechnics         Operations, finance, and compliance
4  Meridian BioLogistics         Operations, finance, and compliance

                                  subject_line  \
0         April Biological-Unit Reconciliation
1  Secure Delivery Record-Handling Instruction
2        Restricted CHAMELEO Governance Review
3            Internal Operations Memorandum 56
4        Internal  Operations  Memorandum  57

                                                text related_purchase_order  \
0  SUBJECT\nUnresolved biological-unit imbalance ...                    NaN
1  SCOPE\nThis instruction applies to staff handl...                    NaN
2  MEETING RECORD — RESTRICTED GOVERNANCE REVIEW\...                    NaN
3  SUBJECT\nOperational review of cold-chain reco...                    NaN
4  SUBJECT\nOperational review of supplier onboar...                    NaN

  related_shipment_number related_case_number visibility_level
0                     NaN                 NaN       restricted
1          SHP-2022-00011                 NaN       restricted
2          SHP-2023-00035                 NaN       restricted
3          SHP-2020-00019                 NaN       restricted
4                     NaN                 NaN         internal

In [7]:
df_pr['document_date'] = pd.to_datetime(df_pr['document_date'], format='mixed')
df_pr['document_year'] = df_pr['document_date'].dt.year
df_pr['document_month'] = df_pr['document_date'].dt.month
df_pr['document_day'] = df_pr['document_date'].dt.day
df_pr = df_pr.drop(columns=["document_date"])
print(df_pr.head())

   document_id          document_type     author_name    author_organization  \
0       510062  inventory_explanation      Soren Kade  Meridian BioLogistics
1       510100   security_instruction      Soren Kade  Meridian BioLogistics
2       510101         meeting_record      Soren Kade  Meridian BioLogistics
3       510128    internal_memorandum  Adrian Vosmere    Vosmere Biotechnics
4       510069    internal_memorandum  Dr. Elias Voss  Meridian BioLogistics

                               recipient_text  \
0  Restricted operations and compliance group
1  Restricted operations and compliance group
2  Restricted operations and compliance group
3         Operations, finance, and compliance
4         Operations, finance, and compliance

                                  subject_line  \
0         April Biological-Unit Reconciliation
1  Secure Delivery Record-Handling Instruction
2        Restricted CHAMELEO Governance Review
3            Internal Operations Memorandum 56
4        Internal  Operations  Memorandum  57

                                                text related_purchase_order  \
0  SUBJECT\nUnresolved biological-unit imbalance ...                    NaN
1  SCOPE\nThis instruction applies to staff handl...                    NaN
2  MEETING RECORD — RESTRICTED GOVERNANCE REVIEW\...                    NaN
3  SUBJECT\nOperational review of cold-chain reco...                    NaN
4  SUBJECT\nOperational review of supplier onboar...                    NaN

  related_shipment_number related_case_number visibility_level  document_year  \
0                     NaN                 NaN       restricted           2024
1          SHP-2022-00011                 NaN       restricted           2023
2          SHP-2023-00035                 NaN       restricted           2025
3          SHP-2020-00019                 NaN       restricted           2018
4                     NaN                 NaN         internal           2021

   document_month  document_day
0               4            30
1               8            17
2               3            14
3               5            15
4              10            22

In [8]:
# def extract_document_type(text):
#     text = str(text).strip().upper()

#     if text.startswith("SUBJECT"):
#         return "SUBJECT"
#     elif text.startswith("SCOPE"):
#         return "SCOPE"
#     elif text.startswith("MEETING RECORD"):
#         return "MEETING"
#     elif text.startswith("REQUEST"):
#         return "REQUEST"
#     elif text.startswith("ROUTE"):
#         return "ROUTE"
#     elif text.startswith("PERIOD"):
#         return "PERIOD"
#     else:
#         return "OTHER"


# df_pr["document_type"] = df["text"].apply(extract_document_type)
# df_pr = df_pr.drop('text', axis=1)

## licensed_facilities.csv

on enleve cette tab car elle est vide elle ne contient rien

In [9]:
# Valeurs manquantes
print("valeurs manquantes:")
print(df_lf.isna().sum())

# Nombre de valeurs uniques
print("valeurs uniques")
print(df_lf.nunique())

valeurs manquantes:
facility_license_number                0
facility_name                          0
facility_category                      0
operating_organization_registration    0
street_address                         0
region                                 0
latitude                               0
longitude                              0
license_start                          0
license_end                            3
facility_status                        0
declared_services                      0
dtype: int64
valeurs uniques
facility_license_number                3
facility_name                          3
facility_category                      3
operating_organization_registration    2
street_address                         3
region                                 2
latitude                               3
longitude                              3
license_start                          3
license_end                            0
facility_status                        1
declared_services                      3
dtype: int64

In [10]:
df_lf = df_lf.drop('license_end', axis=1)
df_lf = df_lf.drop('facility_status', axis=1)

In [11]:
df_lf['license_start'] = pd.to_datetime(df_lf['license_start'], format='mixed')
df_lf['license_start_year'] = df_lf['license_start'].dt.year
df_lf['license_start_month'] = df_lf['license_start'].dt.month
df_lf['license_start_day'] = df_lf['license_start'].dt.day
df_lf = df_lf.drop(columns=["license_start"])
print(df_lf.head())

  facility_license_number                       facility_name  \
0             FAC-VLN-101    Asterion Central Clinical Campus
1             FAC-AVL-201   Asterion Avelora Executive Clinic
2             FAC-AVL-301  Threshold Earth Avelora Laboratory

     facility_category operating_organization_registration  \
0    research_hospital                       REG-VLN-01002
1       private_clinic                       REG-VLN-01002
2  research_laboratory                       REG-AVL-01007

                                      street_address              region  \
0  Asterion Central Clinical Campus, Valenne Cent...    Valenne Republic
1  Asterion Avelora Executive Clinic, Eastern Ave...  Avelora Federation
2  Threshold Earth Avelora Laboratory, Eastern Av...  Avelora Federation

   latitude  longitude                                  declared_services  \
0     47.20       7.51  preventive medicine; cardiac assessment; clini...
1      7.35     101.62  executive health; specialist follow-up; outpat...
2      7.50     101.75  environmental health research; non-invasive hu...

   license_start_year  license_start_month  license_start_day
0                2001                    2                  1
1                2008                    5                 15
2                2012                    1                 18

In [12]:
df_lf['facility_license_number'] = df_lf['facility_license_number'].str.replace("FAC-", "", regex=False).astype(str)
print(df_lf.head())

  facility_license_number                       facility_name  \
0                 VLN-101    Asterion Central Clinical Campus
1                 AVL-201   Asterion Avelora Executive Clinic
2                 AVL-301  Threshold Earth Avelora Laboratory

     facility_category operating_organization_registration  \
0    research_hospital                       REG-VLN-01002
1       private_clinic                       REG-VLN-01002
2  research_laboratory                       REG-AVL-01007

                                      street_address              region  \
0  Asterion Central Clinical Campus, Valenne Cent...    Valenne Republic
1  Asterion Avelora Executive Clinic, Eastern Ave...  Avelora Federation
2  Threshold Earth Avelora Laboratory, Eastern Av...  Avelora Federation

   latitude  longitude                                  declared_services  \
0     47.20       7.51  preventive medicine; cardiac assessment; clini...
1      7.35     101.62  executive health; specialist follow-up; outpat...
2      7.50     101.75  environmental health research; non-invasive hu...

   license_start_year  license_start_month  license_start_day
0                2001                    2                  1
1                2008                    5                 15
2                2012                    1                 18

In [13]:
df_lf['operating_organization_registration'] = df_lf['operating_organization_registration'].str.replace("REG-", "", regex=False).astype(str)

## licensed_professionals.csv

In [14]:
# Valeurs manquantes
print(df_lp.isna().sum())
print(len(df_lp))

# Nombre de valeurs uniques
print(df_lp.nunique())

license_number               0
professional_name            0
profession                   0
specialty                    0
license_issue_date           0
license_expiry_date         53
license_status               0
primary_facility_license    26
registered_region            0
disciplinary_status          0
dtype: int64
53
license_number              53
professional_name           53
profession                   5
specialty                   16
license_issue_date          40
license_expiry_date          0
license_status               1
primary_facility_license     3
registered_region            5
disciplinary_status          2
dtype: int64

In [15]:
print(df_lp.columns)

Index(['license_number', 'professional_name', 'profession', 'specialty',
       'license_issue_date', 'license_expiry_date', 'license_status',
       'primary_facility_license', 'registered_region', 'disciplinary_status'],
      dtype='object')

on a décidé de les supprimer car ils ont tous la même valeur ou sont vides

In [16]:
df_lp = df_lp.drop('license_status', axis=1)
df_lp = df_lp.drop('license_expiry_date', axis=1)

In [17]:
df_lp['license_issue_date'] = pd.to_datetime(df_lp['license_issue_date'], format='mixed')
df_lp['license_issue_year'] = df_lp['license_issue_date'].dt.year
df_lp['license_issue_month'] = df_lp['license_issue_date'].dt.month
df_lp['license_issue_day'] = df_lp['license_issue_date'].dt.day
df_lp = df_lp.drop(columns=["license_issue_date"])
print(df_lp.head())

     license_number professional_name profession            specialty  \
0  LIC-VLN-MED-1001       Emil Warden  physician           cardiology
1  LIC-VLN-MED-1002   Dr. Naima Orrel  physician  preventive medicine
2  LIC-VLN-MED-1003    Dr. Corin Hale  physician      cardiac imaging
3  LIC-VLN-MED-1004     Dr. Lysa Quen  physician        medical audit
4  LIC-VLN-MED-1005        Faris Uren  physician           cardiology

  primary_facility_license registered_region disciplinary_status  \
0              FAC-VLN-101          Valennan                none
1              FAC-VLN-101          Valennan                none
2              FAC-AVL-201          Valennan                none
3              FAC-VLN-101          Valennan                none
4              FAC-VLN-101          Valennan                none

   license_issue_year  license_issue_month  license_issue_day
0                1895                    7                  1
1                2002                    7                  1
2                2002                    7                  1
3                1995                    7                  1
4                1986                    7                  1

In [18]:
df_lp['primary_facility_license'] = df_lp['primary_facility_license'].str.replace("FAC-", "", regex=False).astype(str)
print(df_lp.head())

     license_number professional_name profession            specialty  \
0  LIC-VLN-MED-1001       Emil Warden  physician           cardiology
1  LIC-VLN-MED-1002   Dr. Naima Orrel  physician  preventive medicine
2  LIC-VLN-MED-1003    Dr. Corin Hale  physician      cardiac imaging
3  LIC-VLN-MED-1004     Dr. Lysa Quen  physician        medical audit
4  LIC-VLN-MED-1005        Faris Uren  physician           cardiology

  primary_facility_license registered_region disciplinary_status  \
0                  VLN-101          Valennan                none
1                  VLN-101          Valennan                none
2                  AVL-201          Valennan                none
3                  VLN-101          Valennan                none
4                  VLN-101          Valennan                none

   license_issue_year  license_issue_month  license_issue_day
0                1895                    7                  1
1                2002                    7                  1
2                2002                    7                  1
3                1995                    7                  1
4                1986                    7                  1

In [19]:
df_lp['license_number'] = df_lp['license_number'].str.replace("LIC-", "", regex=False).astype(str)
print(df_lp.head())

  license_number professional_name profession            specialty  \
0   VLN-MED-1001       Emil Warden  physician           cardiology
1   VLN-MED-1002   Dr. Naima Orrel  physician  preventive medicine
2   VLN-MED-1003    Dr. Corin Hale  physician      cardiac imaging
3   VLN-MED-1004     Dr. Lysa Quen  physician        medical audit
4   VLN-MED-1005        Faris Uren  physician           cardiology

  primary_facility_license registered_region disciplinary_status  \
0                  VLN-101          Valennan                none
1                  VLN-101          Valennan                none
2                  AVL-201          Valennan                none
3                  VLN-101          Valennan                none
4                  VLN-101          Valennan                none

   license_issue_year  license_issue_month  license_issue_day
0                1895                    7                  1
1                2002                    7                  1
2                2002                    7                  1
3                1995                    7                  1
4                1986                    7                  1

In [20]:
df_lp = pd.get_dummies(df_lp, columns=['profession', 'primary_facility_license', 'registered_region'], prefix='', prefix_sep='', dtype=int)
display(df_lp.head())

,license_number,professional_name,specialty,disciplinary_status,license_issue_year,license_issue_month,license_issue_day,environmental professional,legal professional,physician,...,research professional,AVL-201,AVL-301,VLN-101,nan,Aveloran,Kintaran,Nordhaven,Tembaran,Valennan
0,VLN-MED-1001,Emil Warden,cardiology,none,1895,7,1,0,0,1,...,0,0,0,1,0,0,0,0,0,1
1,VLN-MED-1002,Dr. Naima Orrel,preventive medicine,none,2002,7,1,0,0,1,...,0,0,0,1,0,0,0,0,0,1
2,VLN-MED-1003,Dr. Corin Hale,cardiac imaging,none,2002,7,1,0,0,1,...,0,1,0,0,0,0,0,0,0,1
3,VLN-MED-1004,Dr. Lysa Quen,medical audit,none,1995,7,1,0,0,1,...,0,0,0,1,0,0,0,0,0,1
4,VLN-MED-1005,Faris Uren,cardiology,none,1986,7,1,0,0,1,...,0,0,0,1,0,0,0,0,0,1

In [90]:
print("valeurs uniques")
print(df_lp.nunique())

valeurs uniques
license_number                        53
professional_name                     53
specialty                             16
disciplinary_status                    2
license_issue_year                    39
license_issue_month                    2
license_issue_day                      2
environmental professional             2
legal professional                     2
physician                              2
public administration professional     2
research professional                  2
AVL-201                                2
AVL-301                                2
VLN-101                                2
nan                                    2
Aveloran                               2
Kintaran                               2
Nordhaven                              2
Tembaran                               2
Valennan                               2
dtype: int64

## officer_filings.csv

In [21]:
# Valeurs manquantes
print("valeurs manquantes:")
print(df_of.isna().sum())

# Nombre de valeurs uniques
print("valeurs uniques")
print(df_of.nunique())

valeurs manquantes:
filing_id                  0
registration_number        0
officer_local_ref          0
full_name                  0
birth_year_or_age_band     0
nationality_or_region      0
role_title                 0
appointment_date           0
cessation_date            77
filing_date                0
service_address            0
filing_status              0
dtype: int64
valeurs uniques
filing_id                 135
registration_number        24
officer_local_ref         104
full_name                 105
birth_year_or_age_band     50
nationality_or_region       5
role_title                 54
appointment_date           53
cessation_date             37
filing_date               133
service_address            12
filing_status               2
dtype: int64

on enleve le FLG- qui ne sert pas à grand chose
REG- et OFR aussi

In [22]:
print(df_of.columns)

Index(['filing_id', 'registration_number', 'officer_local_ref', 'full_name',
       'birth_year_or_age_band', 'nationality_or_region', 'role_title',
       'appointment_date', 'cessation_date', 'filing_date', 'service_address',
       'filing_status'],
      dtype='object')

In [23]:
#pas d'erreur c'est juste qu'on peut le faire qu'une fois
df_of['filing_id'] = df_of['filing_id'].str.replace("FLG-", "", regex=False).astype(int)
print(df_of.head())

   filing_id registration_number officer_local_ref       full_name  \
0          1       REG-NDH-01015         OFR-20001     Edward Vann
1          2       REG-VLN-01016         OFR-20002     Emil Warden
2          3       REG-NDH-01017         OFR-20003  Adrian Vosmere
3          4       REG-VLN-01001         OFR-20004  Dr. Elias Voss
4          5       REG-KNT-01018         OFR-20005       J. Varlan

  birth_year_or_age_band nationality_or_region  \
0                   1815             Nordhaven
1                   1871              Valennan
2              1920–1929             Nordhaven
3                   1961              Valennan
4                   1862              Kintaran

                                 role_title appointment_date cessation_date  \
0           Industrial and shipping adviser       1840-01-01     1888-12-31
1           Commercial and medical investor       1895-01-01     1943-12-31
2     Biotechnology and logistics executive       1952-01-01     1991-12-31
3  Executive chair of Meridian BioLogistics       1996-01-01            NaN
4             Natural-history correspondent       1885-01-01     1918-12-31

  filing_date                service_address filing_status
0  1840-03-09                Nordhaven Union    historical
1  1895-01-13               Valenne Republic    historical
2  1952-01-16                Nordhaven Union    historical
3  1996-02-15  Meridian Valenne Headquarters        active
4  1885-03-14               Kintara Republic    historical

In [24]:
df_of['registration_number'] = df_of['registration_number'].str.replace("REG-", "", regex=False)
print(df_of.head())

   filing_id registration_number officer_local_ref       full_name  \
0          1           NDH-01015         OFR-20001     Edward Vann
1          2           VLN-01016         OFR-20002     Emil Warden
2          3           NDH-01017         OFR-20003  Adrian Vosmere
3          4           VLN-01001         OFR-20004  Dr. Elias Voss
4          5           KNT-01018         OFR-20005       J. Varlan

  birth_year_or_age_band nationality_or_region  \
0                   1815             Nordhaven
1                   1871              Valennan
2              1920–1929             Nordhaven
3                   1961              Valennan
4                   1862              Kintaran

                                 role_title appointment_date cessation_date  \
0           Industrial and shipping adviser       1840-01-01     1888-12-31
1           Commercial and medical investor       1895-01-01     1943-12-31
2     Biotechnology and logistics executive       1952-01-01     1991-12-31
3  Executive chair of Meridian BioLogistics       1996-01-01            NaN
4             Natural-history correspondent       1885-01-01     1918-12-31

  filing_date                service_address filing_status
0  1840-03-09                Nordhaven Union    historical
1  1895-01-13               Valenne Republic    historical
2  1952-01-16                Nordhaven Union    historical
3  1996-02-15  Meridian Valenne Headquarters        active
4  1885-03-14               Kintara Republic    historical

In [25]:
df_of['officer_local_ref'] = df_of['officer_local_ref'].str.replace("OFR-", "", regex=False)
print(df_of.head())

   filing_id registration_number officer_local_ref       full_name  \
0          1           NDH-01015             20001     Edward Vann
1          2           VLN-01016             20002     Emil Warden
2          3           NDH-01017             20003  Adrian Vosmere
3          4           VLN-01001             20004  Dr. Elias Voss
4          5           KNT-01018             20005       J. Varlan

  birth_year_or_age_band nationality_or_region  \
0                   1815             Nordhaven
1                   1871              Valennan
2              1920–1929             Nordhaven
3                   1961              Valennan
4                   1862              Kintaran

                                 role_title appointment_date cessation_date  \
0           Industrial and shipping adviser       1840-01-01     1888-12-31
1           Commercial and medical investor       1895-01-01     1943-12-31
2     Biotechnology and logistics executive       1952-01-01     1991-12-31
3  Executive chair of Meridian BioLogistics       1996-01-01            NaN
4             Natural-history correspondent       1885-01-01     1918-12-31

  filing_date                service_address filing_status
0  1840-03-09                Nordhaven Union    historical
1  1895-01-13               Valenne Republic    historical
2  1952-01-16                Nordhaven Union    historical
3  1996-02-15  Meridian Valenne Headquarters        active
4  1885-03-14               Kintara Republic    historical

mettre les dates dans le bon format

In [26]:
df_of['appointment_date'] = pd.to_datetime(df_of['appointment_date'], format='%Y-%m-%d', errors='coerce')

date_par_defaut = df_of['appointment_date'].min()
df_of['appointment_date'] = df_of['appointment_date'].fillna(date_par_defaut)

print(f"Date par défaut appliquée automatiquement aux erreurs : {date_par_defaut.strftime('%Y-%m-%d')}")
print(df_of.info())

Date par défaut appliquée automatiquement aux erreurs : 1840-01-01
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 136 entries, 0 to 135
Data columns (total 12 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   filing_id               136 non-null    int64
 1   registration_number     136 non-null    object
 2   officer_local_ref       136 non-null    object
 3   full_name               136 non-null    object
 4   birth_year_or_age_band  136 non-null    object
 5   nationality_or_region   136 non-null    object
 6   role_title              136 non-null    object
 7   appointment_date        136 non-null    datetime64[ns]
 8   cessation_date          59 non-null     object
 9   filing_date             136 non-null    object
 10  service_address         136 non-null    object
 11  filing_status           136 non-null    object
dtypes: datetime64[ns](1), int64(1), object(10)
memory usage: 12.9+ KB
None

birth year or  age band donnne des données trop incohérentes on les divise

In [27]:
#conversion en chaîne de caractères pour le traitement
serie_temp = df_of['birth_year_or_age_band'].astype(str).str.strip()

#année de naissance 4 chiffres
df_of['birth_year'] = np.where(serie_temp.str.match(r'^\d{4}$'), serie_temp, np.nan)

#tranche d'âge (valeur contenant un tiret, ex: 1960-1969)
df_of['age_band'] = np.where(serie_temp.str.contains('-', regex=False), serie_temp, np.nan)

df_of = df_of.drop('birth_year_or_age_band', axis=1)
print(df_of)

     filing_id registration_number officer_local_ref       full_name  \
0            1           NDH-01015             20001     Edward Vann
1            2           VLN-01016             20002     Emil Warden
2            3           NDH-01017             20003  Adrian Vosmere
3            4           VLN-01001             20004  Dr. Elias Voss
4            5           KNT-01018             20005       J. Varlan
..         ...                 ...               ...             ...
131        132           VLN-01021             20128       Xara Aren
132        133           NDH-01022             20129     Miran Istra
133        134           VLN-01004             20129     Miran Istra
134        135           VLN-01023             20130     Miran Soren
135         53           VLN-01004             20051      Nadia Aren

    nationality_or_region                                role_title  \
0               Nordhaven           Industrial and shipping adviser
1                Valennan           Commercial and medical investor
2               Nordhaven     Biotechnology and logistics executive
3                Valennan  Executive chair of Meridian BioLogistics
4                Kintaran             Natural-history correspondent
..                    ...                                       ...
131              Valennan                Corporate affairs director
132             Nordhaven             Maritime operations executive
133             Nordhaven                          Regional adviser
134              Valennan                        Regional executive
135             Nordhaven                        Operations manager

    appointment_date cessation_date filing_date  \
0         1840-01-01     1888-12-31  1840-03-09
1         1895-01-01     1943-12-31  1895-01-13
2         1952-01-01     1991-12-31  1952-01-16
3         1996-01-01            NaN  1996-02-15
4         1885-01-01     1918-12-31  1885-03-14
..               ...            ...         ...
131       2015-01-01     2024-12-31  2015-02-25
132       1989-01-01            NaN  1989-01-29
133       1986-01-01     1988-12-31  1986-02-19
134       2014-01-01            NaN  2014-02-22
135       2010-01-01     2017-12-31  2010-02-03

                   service_address filing_status birth_year age_band
0                  Nordhaven Union    historical       1815      NaN
1                 Valenne Republic    historical       1871      NaN
2                  Nordhaven Union    historical        NaN      NaN
3    Meridian Valenne Headquarters        active       1961      NaN
4                 Kintara Republic    historical       1862      NaN
..                             ...           ...        ...      ...
131               Valenne Republic    historical       1987      NaN
132                Nordhaven Union        active       1962      NaN
133  Meridian Valenne Headquarters    historical       1962      NaN
134               Valenne Republic        active        NaN      NaN
135  Meridian Valenne Headquarters    historical       1986      NaN

[136 rows x 13 columns]

In [28]:
#s'assurer de la conversion des colonnes au format Datetime
app_date = pd.to_datetime(df_of['appointment_date'], errors='coerce')
cess_date = pd.to_datetime(df_of['cessation_date'], errors='coerce')

#calculer la durée des mandats uniquement pour les lignes où la date de cessation existe
durees = (cess_date - app_date).dt.days
durees_valides = durees.dropna()

#Calculer la moyenne et la médiane
moyenne_jours = durees_valides.mean()
mediane_jours = durees_valides.median()

In [29]:

appointment_dt = pd.to_datetime(df_of['appointment_date'], errors='coerce')
cessation_dt = pd.to_datetime(df_of['cessation_date'], errors='coerce')

date_projection = appointment_dt + pd.DateOffset(years=9)

df_of['cessation_date'] = cessation_dt.fillna(date_projection)

filing status est entre active et historical donc on le mets entre 0 et 1 il semble y avoir une erreur dans le format où les valeurs sont stockés ce qui transformait toutes les valeurs en NaN

In [30]:
df_of['filing_status'] = df_of['filing_status'].astype(str).str.strip().str.lower().map({'active': 1, 'historical': 0})
print(df_of['filing_status'].value_counts(dropna=False))

filing_status
1    77
0    59
Name: count, dtype: int64

In [71]:
print(df_of.head())

   filing_id registration_number officer_local_ref       full_name  \
0          1           NDH-01015             20001     Edward Vann
1          2           VLN-01016             20002     Emil Warden
2          3           NDH-01017             20003  Adrian Vosmere
3          4           VLN-01001             20004  Dr. Elias Voss
4          5           KNT-01018             20005       J. Varlan

  nationality_or_region                                role_title  \
0             Nordhaven           Industrial and shipping adviser
1              Valennan           Commercial and medical investor
2             Nordhaven     Biotechnology and logistics executive
3              Valennan  Executive chair of Meridian BioLogistics
4              Kintaran             Natural-history correspondent

                 service_address  filing_status birth_year age_band  \
0                Nordhaven Union              0       1815      NaN
1               Valenne Republic              0       1871      NaN
2                Nordhaven Union              0        NaN      NaN
3  Meridian Valenne Headquarters              1       1961      NaN
4               Kintara Republic              0       1862      NaN

   filing_year  filing_month  filing_day  appointment_year  appointment_month  \
0         1840             3           9              1840                  1
1         1895             1          13              1895                  1
2         1952             1          16              1952                  1
3         1996             2          15              1996                  1
4         1885             3          14              1885                  1

   appointment_day  cessation_year  cessation_month  cessation_day
0                1            1888               12             31
1                1            1943               12             31
2                1            1991               12             31
3                1            2005                1              1
4                1            1918               12             31

In [32]:
df_of['filing_date'] = pd.to_datetime(df_of['filing_date'], format='mixed')
df_of['filing_year'] = df_of['filing_date'].dt.year
df_of['filing_month'] = df_of['filing_date'].dt.month
df_of['filing_day'] = df_of['filing_date'].dt.day
df_of = df_of.drop(columns=["filing_date"])

In [33]:
df_of['appointment_date'] = pd.to_datetime(df_of['appointment_date'], format='mixed')
df_of['appointment_year'] = df_of['appointment_date'].dt.year
df_of['appointment_month'] = df_of['appointment_date'].dt.month
df_of['appointment_day'] = df_of['appointment_date'].dt.day
df_of = df_of.drop(columns=["appointment_date"])

In [34]:
df_of['cessation_date'] = pd.to_datetime(df_of['cessation_date'], format='mixed')
df_of['cessation_year'] = df_of['cessation_date'].dt.year
df_of['cessation_month'] = df_of['cessation_date'].dt.month
df_of['cessation_day'] = df_of['cessation_date'].dt.day
df_of = df_of.drop(columns=["cessation_date"])
print(df_of.head())

   filing_id registration_number officer_local_ref       full_name  \
0          1           NDH-01015             20001     Edward Vann
1          2           VLN-01016             20002     Emil Warden
2          3           NDH-01017             20003  Adrian Vosmere
3          4           VLN-01001             20004  Dr. Elias Voss
4          5           KNT-01018             20005       J. Varlan

  nationality_or_region                                role_title  \
0             Nordhaven           Industrial and shipping adviser
1              Valennan           Commercial and medical investor
2             Nordhaven     Biotechnology and logistics executive
3              Valennan  Executive chair of Meridian BioLogistics
4              Kintaran             Natural-history correspondent

                 service_address  filing_status birth_year age_band  \
0                Nordhaven Union              0       1815      NaN
1               Valenne Republic              0       1871      NaN
2                Nordhaven Union              0        NaN      NaN
3  Meridian Valenne Headquarters              1       1961      NaN
4               Kintara Republic              0       1862      NaN

   filing_year  filing_month  filing_day  appointment_year  appointment_month  \
0         1840             3           9              1840                  1
1         1895             1          13              1895                  1
2         1952             1          16              1952                  1
3         1996             2          15              1996                  1
4         1885             3          14              1885                  1

   appointment_day  cessation_year  cessation_month  cessation_day
0                1            1888               12             31
1                1            1943               12             31
2                1            1991               12             31
3                1            2005                1              1
4                1            1918               12             31

In [76]:
df_of[['registration_type', 'regist_number']] = df_of['registration_number'].str.split('-', n=1, expand=True)
df_of = df_of.drop('registration_number', axis=1)
df_of['regist_number'] = df_of['regist_number'].astype(int)
print(df_of.head())

   filing_id officer_local_ref       full_name nationality_or_region  \
0          1             20001     Edward Vann             Nordhaven
1          2             20002     Emil Warden              Valennan
2          3             20003  Adrian Vosmere             Nordhaven
3          4             20004  Dr. Elias Voss              Valennan
4          5             20005       J. Varlan              Kintaran

                                 role_title                service_address  \
0           Industrial and shipping adviser                Nordhaven Union
1           Commercial and medical investor               Valenne Republic
2     Biotechnology and logistics executive                Nordhaven Union
3  Executive chair of Meridian BioLogistics  Meridian Valenne Headquarters
4             Natural-history correspondent               Kintara Republic

   filing_status birth_year age_band  filing_year  filing_month  filing_day  \
0              0       1815      NaN         1840             3           9
1              0       1871      NaN         1895             1          13
2              0        NaN      NaN         1952             1          16
3              1       1961      NaN         1996             2          15
4              0       1862      NaN         1885             3          14

   appointment_year  appointment_month  appointment_day  cessation_year  \
0              1840                  1                1            1888
1              1895                  1                1            1943
2              1952                  1                1            1991
3              1996                  1                1            2005
4              1885                  1                1            1918

   cessation_month  cessation_day registration_type  regist_number
0               12             31               NDH           1015
1               12             31               VLN           1016
2               12             31               NDH           1017
3                1              1               VLN           1001
4               12             31               KNT           1018

In [81]:
#on peut executer qu'une fois ici aussi
df_of = pd.get_dummies(df_of, columns=['registration_type'], prefix='', prefix_sep='', dtype=int)
display(df_of.head())

KeyError: "None of [Index(['registration_type'], dtype='object')] are in the [columns]"

In [92]:
df_of = df_of.drop(columns=['appointment_day'])

public_and_investigative_documents.csv

## Nettoyage - public and investigate

On a peu de données et de gros blocs de texte
dans la cellule text  

Document id peut être transformé en integer
public or restricted peut être transformé en 0 ou 1 restricted ou public

Je peux pas diviser source reference car je sais pas à quoi correspond ARC

In [35]:
# Valeurs manquantes
print("valeurs manquantes :")
print(df_id.isna().sum())

# Nombre de valeurs uniques
print("valeurs uniques : ")
print(df_id.nunique())

valeurs manquantes :
document_id             0
document_date           0
collection              0
document_type           0
author_name             1
author_organization     0
named_location          0
title                   0
text                    0
public_or_restricted    0
source_reference        0
dtype: int64
valeurs uniques :
document_id             40
document_date           40
collection               6
document_type           16
author_name             32
author_organization     22
named_location          14
title                   40
text                    40
public_or_restricted     2
source_reference        40
dtype: int64

In [36]:
df_id['document_id'] = df_id['document_id'].str.replace("PUB-", "", regex=False).astype(int)
print(df_id.head())

   document_id document_date                collection          document_type  \
0       510045    2022-07-08  investigative_repository  confidential_briefing
1       510094    2024-07-12  investigative_repository       research_summary
2       510043    1942-11-06            public_archive      historical_letter
3       510033    1962-05-18            public_archive        meeting_extract
4       510044    2025-02-21  investigative_repository     investigative_note

     author_name           author_organization  \
0  Dr. Lysa Quen    Orison Medical Audit Board
1    Selene Aras   Threshold Earth Observatory
2    Emil Warden       Warden Medical Ventures
3     Jonah Bell      Bell Conservation Survey
4     Jora Menne  Lantern Investigative Bureau

                       named_location  \
0            Valenne Central District
1  Threshold Earth Avelora Laboratory
2                    Valenne Republic
3                  Avelora Federation
4            Valenne Central District

                                               title  \
0  Restricted Review of Recurrent Executive Healt...
1       Opposed Ecological Strategies and Disclosure
2          Letter from the Vosmere Commercial Papers
3  Extract from the Eastern Orchard Programme Min...
4                Jacob Vale Identity-Continuity Lead

                                                text public_or_restricted  \
0  PURPOSE\nThis restricted briefing summarizes a...           restricted
1  QUESTION\nWhy do two groups using similar ecol...               public
2  6 November 1942\n\nDear M.,\n\nYour note reach...               public
3  EXTRACT FROM MINUTES — 18 MAY 1962\n\nPresent:...               public
4  LEAD\nJacob Vale may be connected to an unusua...           restricted

  source_reference
0    ARC-2022-0103
1    ARC-2024-0107
2    ARC-1942-0108
3    ARC-1962-0109
4    ARC-2025-0111

In [37]:
df_id['document_date'] = pd.to_datetime(df_id['document_date'], format='mixed')
df_id['document_year'] = df_id['document_date'].dt.year
df_id['document_month'] = df_id['document_date'].dt.month
df_id['document_day'] = df_id['document_date'].dt.day
df_id = df_id.drop(columns=["document_date"])
print(df_id.head())

   document_id                collection          document_type  \
0       510045  investigative_repository  confidential_briefing
1       510094  investigative_repository       research_summary
2       510043            public_archive      historical_letter
3       510033            public_archive        meeting_extract
4       510044  investigative_repository     investigative_note

     author_name           author_organization  \
0  Dr. Lysa Quen    Orison Medical Audit Board
1    Selene Aras   Threshold Earth Observatory
2    Emil Warden       Warden Medical Ventures
3     Jonah Bell      Bell Conservation Survey
4     Jora Menne  Lantern Investigative Bureau

                       named_location  \
0            Valenne Central District
1  Threshold Earth Avelora Laboratory
2                    Valenne Republic
3                  Avelora Federation
4            Valenne Central District

                                               title  \
0  Restricted Review of Recurrent Executive Healt...
1       Opposed Ecological Strategies and Disclosure
2          Letter from the Vosmere Commercial Papers
3  Extract from the Eastern Orchard Programme Min...
4                Jacob Vale Identity-Continuity Lead

                                                text public_or_restricted  \
0  PURPOSE\nThis restricted briefing summarizes a...           restricted
1  QUESTION\nWhy do two groups using similar ecol...               public
2  6 November 1942\n\nDear M.,\n\nYour note reach...               public
3  EXTRACT FROM MINUTES — 18 MAY 1962\n\nPresent:...               public
4  LEAD\nJacob Vale may be connected to an unusua...           restricted

  source_reference  document_year  document_month  document_day
0    ARC-2022-0103           2022               7             8
1    ARC-2024-0107           2024               7            12
2    ARC-1942-0108           1942              11             6
3    ARC-1962-0109           1962               5            18
4    ARC-2025-0111           2025               2            21

In [38]:
df_id['public_or_restricted'] = df_id['public_or_restricted'].astype(str).str.strip().str.lower().map({'public': 1, 'restricted': 0})

## public_appointments.csv

## Transformer les données

appointed basis est une cellule pur elle est à supprimer

supprimer APT- de appointment_record_id

appointement end manque de valuers car tout le monde n'est pas forcément parti

source_notice_reference il faudrait enlever NOTICE-

Dans appointment_start il y'a une date qui n'est pas dans le bon format

In [39]:
# Valeurs manquantes
print("valeurs manquantes :")
print(df_pa.isna().sum())

# Nombre de valeurs uniques
print("valeurs uniques : ")
print(df_pa.nunique())

valeurs manquantes :
appointment_record_id       0
appointing_jurisdiction     0
office_holder_name          0
recorded_birth_year         9
office_title                0
institution_name            0
appointment_start           0
appointment_end            34
appointment_basis           0
departure_reason           34
official_region             0
source_notice_reference     0
dtype: int64
valeurs uniques :
appointment_record_id      62
appointing_jurisdiction     4
office_holder_name         50
recorded_birth_year        28
office_title               28
institution_name            9
appointment_start          38
appointment_end            21
appointment_basis           1
departure_reason            3
official_region             4
source_notice_reference    62
dtype: int64

In [40]:
df_pa = df_pa.drop(columns=['appointment_basis'])

In [41]:
df_pa['appointment_record_id'] = df_pa['appointment_record_id'].str.replace("APT-", "", regex=False).astype(int)
print(df_pa.head())

   appointment_record_id appointing_jurisdiction office_holder_name  \
0                      1                Aveloran          Ilyan Rho
1                      2                Kintaran         Amara Senn
2                      3                Kintaran       Leora Kassen
3                      4                Aveloran       Tavian Serat
4                      5                Tembaran       Mirek Talven

   recorded_birth_year                                       office_title  \
0               1975.0  Regional pollinator and agricultural technical...
1               1980.0                      Cave-access programme manager
2               1947.0             Head of government of Kintara Republic
3               1953.0          Senior minister of the Avelora Federation
4               1942.0      Regional governor in the Tembara Commonwealth

                          institution_name appointment_start appointment_end  \
0   Avelora Agricultural Resilience Agency        2003-01-01             NaN
1    Kintara Cave and Pollinator Authority        2005-01-01             NaN
2         Office of the Kintara Chancellor        1978-01-01             NaN
3  Avelora Ministry of Strategic Resources        1984-01-01             NaN
4           Tembara Coastal Administration        01/01/1974             NaN

  departure_reason official_region source_notice_reference
0              NaN        Aveloran    NOTICE-AVL-2003-0002
1              NaN        Kintaran    NOTICE-KNT-2005-0003
2              NaN        Kintaran    NOTICE-KNT-1978-0004
3              NaN        Aveloran    NOTICE-AVL-1984-0005
4              NaN        Tembaran    NOTICE-TMB-1974-0006

In [42]:
df_pa['source_notice_reference'] = df_pa['source_notice_reference'].str.replace("NOTICE-", "", regex=False)
print(df_pa.head())

   appointment_record_id appointing_jurisdiction office_holder_name  \
0                      1                Aveloran          Ilyan Rho
1                      2                Kintaran         Amara Senn
2                      3                Kintaran       Leora Kassen
3                      4                Aveloran       Tavian Serat
4                      5                Tembaran       Mirek Talven

   recorded_birth_year                                       office_title  \
0               1975.0  Regional pollinator and agricultural technical...
1               1980.0                      Cave-access programme manager
2               1947.0             Head of government of Kintara Republic
3               1953.0          Senior minister of the Avelora Federation
4               1942.0      Regional governor in the Tembara Commonwealth

                          institution_name appointment_start appointment_end  \
0   Avelora Agricultural Resilience Agency        2003-01-01             NaN
1    Kintara Cave and Pollinator Authority        2005-01-01             NaN
2         Office of the Kintara Chancellor        1978-01-01             NaN
3  Avelora Ministry of Strategic Resources        1984-01-01             NaN
4           Tembara Coastal Administration        01/01/1974             NaN

  departure_reason official_region source_notice_reference
0              NaN        Aveloran           AVL-2003-0002
1              NaN        Kintaran           KNT-2005-0003
2              NaN        Kintaran           KNT-1978-0004
3              NaN        Aveloran           AVL-1984-0005
4              NaN        Tembaran           TMB-1974-0006

In [43]:
df_pa['appointment_start'] = pd.to_datetime(df_pa['appointment_start'], format='mixed')
df_pa['appointment_year'] = df_pa['appointment_start'].dt.year
df_pa['appointment_month'] = df_pa['appointment_start'].dt.month
df_pa['appointment_day'] = df_pa['appointment_start'].dt.day
df_pa = df_pa.drop(columns=["appointment_start"])

In [44]:
df_pa['appointment_end'] = pd.to_datetime(df_pa['appointment_end'], format='mixed')
df_pa['appointment_end_year'] = df_pa['appointment_end'].dt.year
df_pa['appointment_end_month'] = df_pa['appointment_end'].dt.month
df_pa['appointment_end_day'] = df_pa['appointment_end'].dt.day
df_pa = df_pa.drop(columns=["appointment_end"])
print(df_pa.head())

   appointment_record_id appointing_jurisdiction office_holder_name  \
0                      1                Aveloran          Ilyan Rho
1                      2                Kintaran         Amara Senn
2                      3                Kintaran       Leora Kassen
3                      4                Aveloran       Tavian Serat
4                      5                Tembaran       Mirek Talven

   recorded_birth_year                                       office_title  \
0               1975.0  Regional pollinator and agricultural technical...
1               1980.0                      Cave-access programme manager
2               1947.0             Head of government of Kintara Republic
3               1953.0          Senior minister of the Avelora Federation
4               1942.0      Regional governor in the Tembara Commonwealth

                          institution_name departure_reason official_region  \
0   Avelora Agricultural Resilience Agency              NaN        Aveloran
1    Kintara Cave and Pollinator Authority              NaN        Kintaran
2         Office of the Kintara Chancellor              NaN        Kintaran
3  Avelora Ministry of Strategic Resources              NaN        Aveloran
4           Tembara Coastal Administration              NaN        Tembaran

  source_notice_reference  appointment_year  appointment_month  \
0           AVL-2003-0002              2003                  1
1           KNT-2005-0003              2005                  1
2           KNT-1978-0004              1978                  1
3           AVL-1984-0005              1984                  1
4           TMB-1974-0006              1974                  1

   appointment_day  appointment_end_year  appointment_end_month  \
0                1                   NaN                    NaN
1                1                   NaN                    NaN
2                1                   NaN                    NaN
3                1                   NaN                    NaN
4                1                   NaN                    NaN

   appointment_end_day
0                  NaN
1                  NaN
2                  NaN
3                  NaN
4                  NaN

dates de type float int serait mieux

In [45]:
df_pa['recorded_birth_year'] = df_pa['recorded_birth_year'].astype('Int64')
print(df_pa.head())

   appointment_record_id appointing_jurisdiction office_holder_name  \
0                      1                Aveloran          Ilyan Rho
1                      2                Kintaran         Amara Senn
2                      3                Kintaran       Leora Kassen
3                      4                Aveloran       Tavian Serat
4                      5                Tembaran       Mirek Talven

   recorded_birth_year                                       office_title  \
0                 1975  Regional pollinator and agricultural technical...
1                 1980                      Cave-access programme manager
2                 1947             Head of government of Kintara Republic
3                 1953          Senior minister of the Avelora Federation
4                 1942      Regional governor in the Tembara Commonwealth

                          institution_name departure_reason official_region  \
0   Avelora Agricultural Resilience Agency              NaN        Aveloran
1    Kintara Cave and Pollinator Authority              NaN        Kintaran
2         Office of the Kintara Chancellor              NaN        Kintaran
3  Avelora Ministry of Strategic Resources              NaN        Aveloran
4           Tembara Coastal Administration              NaN        Tembaran

  source_notice_reference  appointment_year  appointment_month  \
0           AVL-2003-0002              2003                  1
1           KNT-2005-0003              2005                  1
2           KNT-1978-0004              1978                  1
3           AVL-1984-0005              1984                  1
4           TMB-1974-0006              1974                  1

   appointment_day  appointment_end_year  appointment_end_month  \
0                1                   NaN                    NaN
1                1                   NaN                    NaN
2                1                   NaN                    NaN
3                1                   NaN                    NaN
4                1                   NaN                    NaN

   appointment_end_day
0                  NaN
1                  NaN
2                  NaN
3                  NaN
4                  NaN

In [96]:
print("valeurs uniques : ")
print(df_pa.nunique())

valeurs uniques :
appointment_record_id      62
appointing_jurisdiction     4
office_holder_name         50
recorded_birth_year        28
office_title               28
institution_name            9
departure_reason            3
source_notice_reference    62
appointment_year           33
appointment_month           6
appointment_day             2
appointment_end_year       21
appointment_end_month       5
appointment_end_day         2
dtype: int64

In [83]:
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
from scipy.stats import chi2_contingency

#table de contingence, fréquences croisées
contingency_table = pd.crosstab(df_pa['appointing_jurisdiction'], df_pa['official_region'])
print("--- Table de contingence (Effectifs croisés) ---")
display(contingency_table)

--- Table de contingence (Effectifs croisés) ---

official_region          Aveloran  Kintaran  Tembaran  Valennan
appointing_jurisdiction
Aveloran                       18         0         0         0
Kintaran                        0        20         0         0
Tembaran                        0         0        11         0
Valennan                        0         0         0        13

In [86]:
# Suppression de la colonne redondante official_region car pareil que la juridiction
df_pa = df_pa.drop(columns=['official_region'])

registered_entities.csv

In [46]:
# Valeurs manquantes
print("valeurs manquantes:")
print(df_re.isna().sum())

# Nombre de valeurs uniques
print("valeurs uniques")
print(df_re.nunique())

valeurs manquantes:
registration_number            0
legal_name                     0
registered_entity_type         0
registration_date              0
current_status                 0
registered_address             0
jurisdiction                   0
declared_activity              0
parent_registration_number    24
last_filing_date               0
dtype: int64
valeurs uniques
registration_number           24
legal_name                    24
registered_entity_type        13
registration_date             22
current_status                 2
registered_address            12
jurisdiction                   5
declared_activity             24
parent_registration_number     0
last_filing_date               7
dtype: int64

### Nous remarquons que "parent_registration_number" est 100% vide, on le supprime

> Add blockquote

In [47]:
df_re=df_re.drop(columns=["parent_registration_number"])

In [48]:
df_re['registration_number'] = df_re['registration_number'].str.replace("REG-", "", regex=False).astype(str)
print(df_re.head())

  registration_number                          legal_name  \
0           VLN-01001               Meridian BioLogistics
1           VLN-01002         Asterion Clinical Institute
2           TMB-01003       Northstar Cold Chain Services
3           VLN-01004       Whitehaven Strategic Holdings
4           VLN-01005  Valenne Industrial Futures Council

  registered_entity_type registration_date current_status  \
0      logistics_company        1996-01-15         active
1     research_institute        1989-01-15         active
2      logistics_company        1992-01-15         active
3     consulting_company        1987-01-15         active
4      trade_association        1984-01-15         active

                 registered_address          jurisdiction  \
0     Meridian Valenne Headquarters      Valenne Republic
1  Asterion Central Clinical Campus      Valenne Republic
2  Northstar Tembara Cold-Chain Hub  Tembara Commonwealth
3     Meridian Valenne Headquarters      Valenne Republic
4          Valenne Central District      Valenne Republic

                                   declared_activity last_filing_date
0  International biological and cold-chain logistics       2025-03-31
1  Private preventive-medicine and research insti...       2025-03-31
2                    Refrigerated transport provider       2025-03-31
3                  Investment and consulting company       2025-03-31
4                        Industry-policy association       2025-03-31

In [49]:
df_re[['registration_type', 'regist_number']] = df_re['registration_number'].str.split('-', n=1, expand=True)
df_re = df_re.drop('registration_number', axis=1)

In [50]:
df_re['regist_number'] = df_re['regist_number'].astype(int)
print(df_re.head())

                           legal_name registered_entity_type  \
0               Meridian BioLogistics      logistics_company
1         Asterion Clinical Institute     research_institute
2       Northstar Cold Chain Services      logistics_company
3       Whitehaven Strategic Holdings     consulting_company
4  Valenne Industrial Futures Council      trade_association

  registration_date current_status                registered_address  \
0        1996-01-15         active     Meridian Valenne Headquarters
1        1989-01-15         active  Asterion Central Clinical Campus
2        1992-01-15         active  Northstar Tembara Cold-Chain Hub
3        1987-01-15         active     Meridian Valenne Headquarters
4        1984-01-15         active          Valenne Central District

           jurisdiction                                  declared_activity  \
0      Valenne Republic  International biological and cold-chain logistics
1      Valenne Republic  Private preventive-medicine and research insti...
2  Tembara Commonwealth                    Refrigerated transport provider
3      Valenne Republic                  Investment and consulting company
4      Valenne Republic                        Industry-policy association

  last_filing_date registration_type  regist_number
0       2025-03-31               VLN           1001
1       2025-03-31               VLN           1002
2       2025-03-31               TMB           1003
3       2025-03-31               VLN           1004
4       2025-03-31               VLN           1005

In [51]:
map = {"active": 1, "dissolved": 0}
df_re['current_status'] = df_re['current_status'].map(map).astype(int)

In [52]:
df_re['last_filing_date'] = pd.to_datetime(df_re['last_filing_date'], format='mixed')
print(df_re.head())
df_re['last_filing_year'] = df_re['last_filing_date'].dt.year
df_re['last_filing_month'] = df_re['last_filing_date'].dt.month
df_re['last_filing_day'] = df_re['last_filing_date'].dt.day
df_re = df_re.drop(columns=["last_filing_date"])
print(df_re.head())

                           legal_name registered_entity_type  \
0               Meridian BioLogistics      logistics_company
1         Asterion Clinical Institute     research_institute
2       Northstar Cold Chain Services      logistics_company
3       Whitehaven Strategic Holdings     consulting_company
4  Valenne Industrial Futures Council      trade_association

  registration_date  current_status                registered_address  \
0        1996-01-15               1     Meridian Valenne Headquarters
1        1989-01-15               1  Asterion Central Clinical Campus
2        1992-01-15               1  Northstar Tembara Cold-Chain Hub
3        1987-01-15               1     Meridian Valenne Headquarters
4        1984-01-15               1          Valenne Central District

           jurisdiction                                  declared_activity  \
0      Valenne Republic  International biological and cold-chain logistics
1      Valenne Republic  Private preventive-medicine and research insti...
2  Tembara Commonwealth                    Refrigerated transport provider
3      Valenne Republic                  Investment and consulting company
4      Valenne Republic                        Industry-policy association

  last_filing_date registration_type  regist_number
0       2025-03-31               VLN           1001
1       2025-03-31               VLN           1002
2       2025-03-31               TMB           1003
3       2025-03-31               VLN           1004
4       2025-03-31               VLN           1005
                           legal_name registered_entity_type  \
0               Meridian BioLogistics      logistics_company
1         Asterion Clinical Institute     research_institute
2       Northstar Cold Chain Services      logistics_company
3       Whitehaven Strategic Holdings     consulting_company
4  Valenne Industrial Futures Council      trade_association

  registration_date  current_status                registered_address  \
0        1996-01-15               1     Meridian Valenne Headquarters
1        1989-01-15               1  Asterion Central Clinical Campus
2        1992-01-15               1  Northstar Tembara Cold-Chain Hub
3        1987-01-15               1     Meridian Valenne Headquarters
4        1984-01-15               1          Valenne Central District

           jurisdiction                                  declared_activity  \
0      Valenne Republic  International biological and cold-chain logistics
1      Valenne Republic  Private preventive-medicine and research insti...
2  Tembara Commonwealth                    Refrigerated transport provider
3      Valenne Republic                  Investment and consulting company
4      Valenne Republic                        Industry-policy association

  registration_type  regist_number  last_filing_year  last_filing_month  \
0               VLN           1001              2025                  3
1               VLN           1002              2025                  3
2               TMB           1003              2025                  3
3               VLN           1004              2025                  3
4               VLN           1005              2025                  3

   last_filing_day
0               31
1               31
2               31
3               31
4               31

In [53]:
df_re['registration_date'] = pd.to_datetime(df_re['registration_date'], format='mixed')
df_re['registration_year'] = df_re['registration_date'].dt.year
df_re['registration_month'] = df_re['registration_date'].dt.month
df_re['registration_day'] = df_re['registration_date'].dt.day
df_re = df_re.drop(columns=["registration_date"])
print(df_re.head())

                           legal_name registered_entity_type  current_status  \
0               Meridian BioLogistics      logistics_company               1
1         Asterion Clinical Institute     research_institute               1
2       Northstar Cold Chain Services      logistics_company               1
3       Whitehaven Strategic Holdings     consulting_company               1
4  Valenne Industrial Futures Council      trade_association               1

                 registered_address          jurisdiction  \
0     Meridian Valenne Headquarters      Valenne Republic
1  Asterion Central Clinical Campus      Valenne Republic
2  Northstar Tembara Cold-Chain Hub  Tembara Commonwealth
3     Meridian Valenne Headquarters      Valenne Republic
4          Valenne Central District      Valenne Republic

                                   declared_activity registration_type  \
0  International biological and cold-chain logistics               VLN
1  Private preventive-medicine and research insti...               VLN
2                    Refrigerated transport provider               TMB
3                  Investment and consulting company               VLN
4                        Industry-policy association               VLN

   regist_number  last_filing_year  last_filing_month  last_filing_day  \
0           1001              2025                  3               31
1           1002              2025                  3               31
2           1003              2025                  3               31
3           1004              2025                  3               31
4           1005              2025                  3               31

   registration_year  registration_month  registration_day
0               1996                   1                15
1               1989                   1                15
2               1992                   1                15
3               1987                   1                15
4               1984                   1                15

In [88]:
df_re = df_re.drop(columns=['registration_month', 'registration_day', 'last_filing_day'])

In [99]:
#on peut executer qu'une fois ici aussi
df_re = pd.get_dummies(df_re, columns=['registration_type'], prefix='', prefix_sep='', dtype=int)
display(df_re.head())

,legal_name,registered_entity_type,current_status,registered_address,jurisdiction,declared_activity,regist_number,last_filing_year,last_filing_month,registration_year,AVL,KNT,NDH,TMB,VLN
0,Meridian BioLogistics,logistics_company,1,Meridian Valenne Headquarters,Valenne Republic,International biological and cold-chain logistics,1001,2025,3,1996,0,0,0,0,1
1,Asterion Clinical Institute,research_institute,1,Asterion Central Clinical Campus,Valenne Republic,Private preventive-medicine and research insti...,1002,2025,3,1989,0,0,0,0,1
2,Northstar Cold Chain Services,logistics_company,1,Northstar Tembara Cold-Chain Hub,Tembara Commonwealth,Refrigerated transport provider,1003,2025,3,1992,0,0,0,1,0
3,Whitehaven Strategic Holdings,consulting_company,1,Meridian Valenne Headquarters,Valenne Republic,Investment and consulting company,1004,2025,3,1987,0,0,0,0,1
4,Valenne Industrial Futures Council,trade_association,1,Valenne Central District,Valenne Republic,Industry-policy association,1005,2025,3,1984,0,0,0,0,1

# regulatory_case_events.csv

In [54]:
print(df_rce.head())

# Valeurs manquantes
print(df_rce.isna().sum())

# Nombre de valeurs uniques
print(df_rce.nunique())

  regulatory_event_id    case_number            case_category  \
0          RGE-000001  REG-2018-0001  environmental_complaint
1          RGE-000002  REG-2018-0001  environmental_complaint
2          RGE-000003  REG-2018-0001  environmental_complaint
3          RGE-000004  REG-2018-0001  environmental_complaint
4          RGE-000005  REG-2018-0001  environmental_complaint

            event_time           activity  \
0  2018-05-14T09:00:00        case_opened
1  2018-05-18T09:00:00  evidence_received
2  2018-05-20T09:00:00      triage_review
3  2018-05-23T09:00:00   technical_review
4  2018-05-27T09:00:00     finding_issued

                             subject_name subject_registration_number  \
0  Avelora Agricultural Resilience Agency                         NaN
1  Avelora Agricultural Resilience Agency                         NaN
2  Avelora Agricultural Resilience Agency                         NaN
3  Avelora Agricultural Resilience Agency                         NaN
4  Avelora Agricultural Resilience Agency                         NaN

                         agency_name       initiating_source  \
0  Tembara Customs Coordination Unit  civil society referral
1  Tembara Customs Coordination Unit  civil society referral
2  Tembara Customs Coordination Unit  civil society referral
3  Tembara Customs Coordination Unit  civil society referral
4  Tembara Customs Coordination Unit  civil society referral

      assigned_unit related_site_code related_shipment_number  \
0  integrity review           AVL-MAR          SHP-2018-00032
1  integrity review           AVL-MAR          SHP-2018-00032
2  integrity review           AVL-MAR          SHP-2018-00032
3  integrity review           AVL-MAR          SHP-2018-00032
4  integrity review           AVL-MAR          SHP-2018-00032

   previous_status       new_status  \
0              new             open
1             open  evidence_review
2  evidence_review         assigned
3         assigned  findings_review
4  findings_review       monitoring

                                             outcome public_reference
0                                    case registered              NaN
1  material received from Lantern Investigative B...              NaN
2                                      case assigned              NaN
3                         technical review completed              NaN
4                   monitoring recommendation issued              NaN
regulatory_event_id              0
case_number                      0
case_category                    0
event_time                       0
activity                         0
subject_name                     0
subject_registration_number     74
agency_name                      0
initiating_source                0
assigned_unit                    0
related_site_code              111
related_shipment_number        141
previous_status                  0
new_status                       0
outcome                          0
public_reference               156
dtype: int64
regulatory_event_id            232
case_number                     40
case_category                    6
event_time                     217
activity                        11
subject_name                    27
subject_registration_number     22
agency_name                      5
initiating_source                2
assigned_unit                    2
related_site_code               16
related_shipment_number         13
previous_status                  9
new_status                       9
outcome                         20
public_reference                13
dtype: int64

In [55]:
df_rce.duplicated().sum()

np.int64(1)

In [56]:
df_rce = df_rce.drop_duplicates()

In [57]:
df_rce['regulatory_event_id'] = df_rce['regulatory_event_id'].str.replace("RGE-", "", regex=False).astype(int)
print(df_rce.head())

   regulatory_event_id    case_number            case_category  \
0                    1  REG-2018-0001  environmental_complaint
1                    2  REG-2018-0001  environmental_complaint
2                    3  REG-2018-0001  environmental_complaint
3                    4  REG-2018-0001  environmental_complaint
4                    5  REG-2018-0001  environmental_complaint

            event_time           activity  \
0  2018-05-14T09:00:00        case_opened
1  2018-05-18T09:00:00  evidence_received
2  2018-05-20T09:00:00      triage_review
3  2018-05-23T09:00:00   technical_review
4  2018-05-27T09:00:00     finding_issued

                             subject_name subject_registration_number  \
0  Avelora Agricultural Resilience Agency                         NaN
1  Avelora Agricultural Resilience Agency                         NaN
2  Avelora Agricultural Resilience Agency                         NaN
3  Avelora Agricultural Resilience Agency                         NaN
4  Avelora Agricultural Resilience Agency                         NaN

                         agency_name       initiating_source  \
0  Tembara Customs Coordination Unit  civil society referral
1  Tembara Customs Coordination Unit  civil society referral
2  Tembara Customs Coordination Unit  civil society referral
3  Tembara Customs Coordination Unit  civil society referral
4  Tembara Customs Coordination Unit  civil society referral

      assigned_unit related_site_code related_shipment_number  \
0  integrity review           AVL-MAR          SHP-2018-00032
1  integrity review           AVL-MAR          SHP-2018-00032
2  integrity review           AVL-MAR          SHP-2018-00032
3  integrity review           AVL-MAR          SHP-2018-00032
4  integrity review           AVL-MAR          SHP-2018-00032

   previous_status       new_status  \
0              new             open
1             open  evidence_review
2  evidence_review         assigned
3         assigned  findings_review
4  findings_review       monitoring

                                             outcome public_reference
0                                    case registered              NaN
1  material received from Lantern Investigative B...              NaN
2                                      case assigned              NaN
3                         technical review completed              NaN
4                   monitoring recommendation issued              NaN

In [58]:
df_rce['case_number'] = df_rce['case_number'].str.replace(r"REG-20\d\d-", "", regex=True).astype(int)
print(df_rce.head())

   regulatory_event_id  case_number            case_category  \
0                    1            1  environmental_complaint
1                    2            1  environmental_complaint
2                    3            1  environmental_complaint
3                    4            1  environmental_complaint
4                    5            1  environmental_complaint

            event_time           activity  \
0  2018-05-14T09:00:00        case_opened
1  2018-05-18T09:00:00  evidence_received
2  2018-05-20T09:00:00      triage_review
3  2018-05-23T09:00:00   technical_review
4  2018-05-27T09:00:00     finding_issued

                             subject_name subject_registration_number  \
0  Avelora Agricultural Resilience Agency                         NaN
1  Avelora Agricultural Resilience Agency                         NaN
2  Avelora Agricultural Resilience Agency                         NaN
3  Avelora Agricultural Resilience Agency                         NaN
4  Avelora Agricultural Resilience Agency                         NaN

                         agency_name       initiating_source  \
0  Tembara Customs Coordination Unit  civil society referral
1  Tembara Customs Coordination Unit  civil society referral
2  Tembara Customs Coordination Unit  civil society referral
3  Tembara Customs Coordination Unit  civil society referral
4  Tembara Customs Coordination Unit  civil society referral

      assigned_unit related_site_code related_shipment_number  \
0  integrity review           AVL-MAR          SHP-2018-00032
1  integrity review           AVL-MAR          SHP-2018-00032
2  integrity review           AVL-MAR          SHP-2018-00032
3  integrity review           AVL-MAR          SHP-2018-00032
4  integrity review           AVL-MAR          SHP-2018-00032

   previous_status       new_status  \
0              new             open
1             open  evidence_review
2  evidence_review         assigned
3         assigned  findings_review
4  findings_review       monitoring

                                             outcome public_reference
0                                    case registered              NaN
1  material received from Lantern Investigative B...              NaN
2                                      case assigned              NaN
3                         technical review completed              NaN
4                   monitoring recommendation issued              NaN

In [59]:
df_rce = df_rce.drop(columns=["public_reference"])

In [60]:
df_rce['event_time'] = pd.to_datetime(df_rce['event_time'], format='mixed')
df_rce['event_year'] = df_rce['event_time'].dt.year
df_rce['event_month'] = df_rce['event_time'].dt.month
df_rce['event_day'] = df_rce['event_time'].dt.day
df_rce['event_hour'] = df_rce['event_time'].dt.hour
df_rce = df_rce.drop(columns=["event_time"])
print(df_rce.head())

   regulatory_event_id  case_number            case_category  \
0                    1            1  environmental_complaint
1                    2            1  environmental_complaint
2                    3            1  environmental_complaint
3                    4            1  environmental_complaint
4                    5            1  environmental_complaint

            activity                            subject_name  \
0        case_opened  Avelora Agricultural Resilience Agency
1  evidence_received  Avelora Agricultural Resilience Agency
2      triage_review  Avelora Agricultural Resilience Agency
3   technical_review  Avelora Agricultural Resilience Agency
4     finding_issued  Avelora Agricultural Resilience Agency

  subject_registration_number                        agency_name  \
0                         NaN  Tembara Customs Coordination Unit
1                         NaN  Tembara Customs Coordination Unit
2                         NaN  Tembara Customs Coordination Unit
3                         NaN  Tembara Customs Coordination Unit
4                         NaN  Tembara Customs Coordination Unit

        initiating_source     assigned_unit related_site_code  \
0  civil society referral  integrity review           AVL-MAR
1  civil society referral  integrity review           AVL-MAR
2  civil society referral  integrity review           AVL-MAR
3  civil society referral  integrity review           AVL-MAR
4  civil society referral  integrity review           AVL-MAR

  related_shipment_number  previous_status       new_status  \
0          SHP-2018-00032              new             open
1          SHP-2018-00032             open  evidence_review
2          SHP-2018-00032  evidence_review         assigned
3          SHP-2018-00032         assigned  findings_review
4          SHP-2018-00032  findings_review       monitoring

                                             outcome  event_year  event_month  \
0                                    case registered        2018            5
1  material received from Lantern Investigative B...        2018            5
2                                      case assigned        2018            5
3                         technical review completed        2018            5
4                   monitoring recommendation issued        2018            5

   event_day  event_hour
0         14           9
1         18           9
2         20           9
3         23           9
4         27           9

In [61]:
df_rce['related_shipment_number'] = df_rce['related_shipment_number'].str.replace(r"SHP-20\d\d-", "", regex=True).astype('Int64')
print(df_rce.head())

   regulatory_event_id  case_number            case_category  \
0                    1            1  environmental_complaint
1                    2            1  environmental_complaint
2                    3            1  environmental_complaint
3                    4            1  environmental_complaint
4                    5            1  environmental_complaint

            activity                            subject_name  \
0        case_opened  Avelora Agricultural Resilience Agency
1  evidence_received  Avelora Agricultural Resilience Agency
2      triage_review  Avelora Agricultural Resilience Agency
3   technical_review  Avelora Agricultural Resilience Agency
4     finding_issued  Avelora Agricultural Resilience Agency

  subject_registration_number                        agency_name  \
0                         NaN  Tembara Customs Coordination Unit
1                         NaN  Tembara Customs Coordination Unit
2                         NaN  Tembara Customs Coordination Unit
3                         NaN  Tembara Customs Coordination Unit
4                         NaN  Tembara Customs Coordination Unit

        initiating_source     assigned_unit related_site_code  \
0  civil society referral  integrity review           AVL-MAR
1  civil society referral  integrity review           AVL-MAR
2  civil society referral  integrity review           AVL-MAR
3  civil society referral  integrity review           AVL-MAR
4  civil society referral  integrity review           AVL-MAR

   related_shipment_number  previous_status       new_status  \
0                       32              new             open
1                       32             open  evidence_review
2                       32  evidence_review         assigned
3                       32         assigned  findings_review
4                       32  findings_review       monitoring

                                             outcome  event_year  event_month  \
0                                    case registered        2018            5
1  material received from Lantern Investigative B...        2018            5
2                                      case assigned        2018            5
3                         technical review completed        2018            5
4                   monitoring recommendation issued        2018            5

   event_day  event_hour
0         14           9
1         18           9
2         20           9
3         23           9
4         27           9

In [62]:
df_rce['subject_registration_number'] = df_rce['subject_registration_number'].str.replace("REG-", "", regex=False).astype(str)
print(df_rce.head())

   regulatory_event_id  case_number            case_category  \
0                    1            1  environmental_complaint
1                    2            1  environmental_complaint
2                    3            1  environmental_complaint
3                    4            1  environmental_complaint
4                    5            1  environmental_complaint

            activity                            subject_name  \
0        case_opened  Avelora Agricultural Resilience Agency
1  evidence_received  Avelora Agricultural Resilience Agency
2      triage_review  Avelora Agricultural Resilience Agency
3   technical_review  Avelora Agricultural Resilience Agency
4     finding_issued  Avelora Agricultural Resilience Agency

  subject_registration_number                        agency_name  \
0                         nan  Tembara Customs Coordination Unit
1                         nan  Tembara Customs Coordination Unit
2                         nan  Tembara Customs Coordination Unit
3                         nan  Tembara Customs Coordination Unit
4                         nan  Tembara Customs Coordination Unit

        initiating_source     assigned_unit related_site_code  \
0  civil society referral  integrity review           AVL-MAR
1  civil society referral  integrity review           AVL-MAR
2  civil society referral  integrity review           AVL-MAR
3  civil society referral  integrity review           AVL-MAR
4  civil society referral  integrity review           AVL-MAR

   related_shipment_number  previous_status       new_status  \
0                       32              new             open
1                       32             open  evidence_review
2                       32  evidence_review         assigned
3                       32         assigned  findings_review
4                       32  findings_review       monitoring

                                             outcome  event_year  event_month  \
0                                    case registered        2018            5
1  material received from Lantern Investigative B...        2018            5
2                                      case assigned        2018            5
3                         technical review completed        2018            5
4                   monitoring recommendation issued        2018            5

   event_day  event_hour
0         14           9
1         18           9
2         20           9
3         23           9
4         27           9

## site_access_case_events.csv

In [63]:
print(df_sac.head())

# Valeurs manquantes
print(df_sac.isna().sum())

# Nombre de valeurs uniques
print(df_sac.nunique())

  access_event_id access_case_number site_code           event_time  \
0      ACE-000001      ACC-2018-0001   TMB-NAC  2018-01-15T09:00:00
1      ACE-000002      ACC-2018-0001   TMB-NAC  2018-01-21T09:00:00
2      ACE-000003      ACC-2018-0001   TMB-NAC  2018-01-26T09:00:00
3      ACE-000004      ACC-2018-0001   TMB-NAC  2018-01-30T09:00:00
4      ACE-000005      ACC-2018-0001   TMB-NAC  2018-02-05T09:00:00

                activity        requesting_organization_name  \
0      request_submitted  Horizon Field Research Cooperative
1       technical_review  Horizon Field Research Cooperative
2        wildlife_review  Horizon Field Research Cooperative
3        security_review  Horizon Field Research Cooperative
4  authorization_granted  Horizon Field Research Cooperative

  requesting_registration_number            authorizing_agency  \
0                  REG-AVL-01013  Tembara Biodiversity Service
1                  REG-AVL-01013  Tembara Biodiversity Service
2                  REG-AVL-01013  Tembara Biodiversity Service
3                  REG-AVL-01013  Tembara Biodiversity Service
4                  REG-AVL-01013  Tembara Biodiversity Service

  authorized_person_name                                 access_purpose  \
0            Bela Ferran  acoustic monitoring and equipment maintenance
1           Kellan Orell  acoustic monitoring and equipment maintenance
2           Jalen Quorin  acoustic monitoring and equipment maintenance
3            Jalen Zorin  acoustic monitoring and equipment maintenance
4              Xara Lask  acoustic monitoring and equipment maintenance

                               equipment_category   previous_status  \
0  portable monitoring and cold-storage equipment             draft
1  portable monitoring and cold-storage equipment         submitted
2  portable monitoring and cold-storage equipment  technical_review
3  portable monitoring and cold-storage equipment   wildlife_review
4  portable monitoring and cold-storage equipment   security_review

         new_status confidentiality_class                            outcome
0         submitted            restricted                     request logged
1  technical_review            restricted         technical review completed
2   wildlife_review            restricted       wildlife conditions recorded
3   security_review            restricted  site-security conditions recorded
4        authorized            restricted               authorization issued
access_event_id                    0
access_case_number                 0
site_code                          0
event_time                         0
activity                           0
requesting_organization_name       0
requesting_registration_number    65
authorizing_agency                 0
authorized_person_name             2
access_purpose                     0
equipment_category                 0
previous_status                    0
new_status                         0
confidentiality_class              0
outcome                            0
dtype: int64
access_event_id                   412
access_case_number                 60
site_code                          50
event_time                        380
activity                           11
requesting_organization_name       31
requesting_registration_number     25
authorizing_agency                  3
authorized_person_name             47
access_purpose                      9
equipment_category                  6
previous_status                    11
new_status                         11
confidentiality_class               3
outcome                            12
dtype: int64

In [64]:
#pas d'erreur c'est juste qu'on peut le faire qu'une fois
df_sac['access_event_id'] = df_sac['access_event_id'].str.replace("ACE-", "", regex=False).astype(int)
print(df_sac.head())

   access_event_id access_case_number site_code           event_time  \
0                1      ACC-2018-0001   TMB-NAC  2018-01-15T09:00:00
1                2      ACC-2018-0001   TMB-NAC  2018-01-21T09:00:00
2                3      ACC-2018-0001   TMB-NAC  2018-01-26T09:00:00
3                4      ACC-2018-0001   TMB-NAC  2018-01-30T09:00:00
4                5      ACC-2018-0001   TMB-NAC  2018-02-05T09:00:00

                activity        requesting_organization_name  \
0      request_submitted  Horizon Field Research Cooperative
1       technical_review  Horizon Field Research Cooperative
2        wildlife_review  Horizon Field Research Cooperative
3        security_review  Horizon Field Research Cooperative
4  authorization_granted  Horizon Field Research Cooperative

  requesting_registration_number            authorizing_agency  \
0                  REG-AVL-01013  Tembara Biodiversity Service
1                  REG-AVL-01013  Tembara Biodiversity Service
2                  REG-AVL-01013  Tembara Biodiversity Service
3                  REG-AVL-01013  Tembara Biodiversity Service
4                  REG-AVL-01013  Tembara Biodiversity Service

  authorized_person_name                                 access_purpose  \
0            Bela Ferran  acoustic monitoring and equipment maintenance
1           Kellan Orell  acoustic monitoring and equipment maintenance
2           Jalen Quorin  acoustic monitoring and equipment maintenance
3            Jalen Zorin  acoustic monitoring and equipment maintenance
4              Xara Lask  acoustic monitoring and equipment maintenance

                               equipment_category   previous_status  \
0  portable monitoring and cold-storage equipment             draft
1  portable monitoring and cold-storage equipment         submitted
2  portable monitoring and cold-storage equipment  technical_review
3  portable monitoring and cold-storage equipment   wildlife_review
4  portable monitoring and cold-storage equipment   security_review

         new_status confidentiality_class                            outcome
0         submitted            restricted                     request logged
1  technical_review            restricted         technical review completed
2   wildlife_review            restricted       wildlife conditions recorded
3   security_review            restricted  site-security conditions recorded
4        authorized            restricted               authorization issued

date reedondant et ACC non utile

In [65]:
df_sac['access_case_number'] = df_sac['access_case_number'].str.replace(r"ACC-20\d\d-", "", regex=True).astype(int)
print(df_sac.head())

   access_event_id  access_case_number site_code           event_time  \
0                1                   1   TMB-NAC  2018-01-15T09:00:00
1                2                   1   TMB-NAC  2018-01-21T09:00:00
2                3                   1   TMB-NAC  2018-01-26T09:00:00
3                4                   1   TMB-NAC  2018-01-30T09:00:00
4                5                   1   TMB-NAC  2018-02-05T09:00:00

                activity        requesting_organization_name  \
0      request_submitted  Horizon Field Research Cooperative
1       technical_review  Horizon Field Research Cooperative
2        wildlife_review  Horizon Field Research Cooperative
3        security_review  Horizon Field Research Cooperative
4  authorization_granted  Horizon Field Research Cooperative

  requesting_registration_number            authorizing_agency  \
0                  REG-AVL-01013  Tembara Biodiversity Service
1                  REG-AVL-01013  Tembara Biodiversity Service
2                  REG-AVL-01013  Tembara Biodiversity Service
3                  REG-AVL-01013  Tembara Biodiversity Service
4                  REG-AVL-01013  Tembara Biodiversity Service

  authorized_person_name                                 access_purpose  \
0            Bela Ferran  acoustic monitoring and equipment maintenance
1           Kellan Orell  acoustic monitoring and equipment maintenance
2           Jalen Quorin  acoustic monitoring and equipment maintenance
3            Jalen Zorin  acoustic monitoring and equipment maintenance
4              Xara Lask  acoustic monitoring and equipment maintenance

                               equipment_category   previous_status  \
0  portable monitoring and cold-storage equipment             draft
1  portable monitoring and cold-storage equipment         submitted
2  portable monitoring and cold-storage equipment  technical_review
3  portable monitoring and cold-storage equipment   wildlife_review
4  portable monitoring and cold-storage equipment   security_review

         new_status confidentiality_class                            outcome
0         submitted            restricted                     request logged
1  technical_review            restricted         technical review completed
2   wildlife_review            restricted       wildlife conditions recorded
3   security_review            restricted  site-security conditions recorded
4        authorized            restricted               authorization issued

In [66]:
df_sac['event_time'] = pd.to_datetime(df_sac['event_time'], format='mixed')
print(df_sac.head())

   access_event_id  access_case_number site_code          event_time  \
0                1                   1   TMB-NAC 2018-01-15 09:00:00
1                2                   1   TMB-NAC 2018-01-21 09:00:00
2                3                   1   TMB-NAC 2018-01-26 09:00:00
3                4                   1   TMB-NAC 2018-01-30 09:00:00
4                5                   1   TMB-NAC 2018-02-05 09:00:00

                activity        requesting_organization_name  \
0      request_submitted  Horizon Field Research Cooperative
1       technical_review  Horizon Field Research Cooperative
2        wildlife_review  Horizon Field Research Cooperative
3        security_review  Horizon Field Research Cooperative
4  authorization_granted  Horizon Field Research Cooperative

  requesting_registration_number            authorizing_agency  \
0                  REG-AVL-01013  Tembara Biodiversity Service
1                  REG-AVL-01013  Tembara Biodiversity Service
2                  REG-AVL-01013  Tembara Biodiversity Service
3                  REG-AVL-01013  Tembara Biodiversity Service
4                  REG-AVL-01013  Tembara Biodiversity Service

  authorized_person_name                                 access_purpose  \
0            Bela Ferran  acoustic monitoring and equipment maintenance
1           Kellan Orell  acoustic monitoring and equipment maintenance
2           Jalen Quorin  acoustic monitoring and equipment maintenance
3            Jalen Zorin  acoustic monitoring and equipment maintenance
4              Xara Lask  acoustic monitoring and equipment maintenance

                               equipment_category   previous_status  \
0  portable monitoring and cold-storage equipment             draft
1  portable monitoring and cold-storage equipment         submitted
2  portable monitoring and cold-storage equipment  technical_review
3  portable monitoring and cold-storage equipment   wildlife_review
4  portable monitoring and cold-storage equipment   security_review

         new_status confidentiality_class                            outcome
0         submitted            restricted                     request logged
1  technical_review            restricted         technical review completed
2   wildlife_review            restricted       wildlife conditions recorded
3   security_review            restricted  site-security conditions recorded
4        authorized            restricted               authorization issued

In [67]:
df_sac['requesting_registration_number'] = df_sac['requesting_registration_number'].str.replace("REG-", "", regex=False).astype(str)

In [68]:
print(df_sac['event_time'].dt.hour)
df_sac['event_hour'] = df_sac['event_time'].dt.hour
df_sac['event_year'] = df_sac['event_time'].dt.year
df_sac['event_month'] = df_sac['event_time'].dt.month
df_sac['event_day'] = df_sac['event_time'].dt.day
df_sac = df_sac.drop(columns=["event_time"])
print(df_sac.head())

0       9
1       9
2       9
3       9
4       9
       ..
408     9
409    17
410    11
411     9
412     9
Name: event_time, Length: 413, dtype: int32
   access_event_id  access_case_number site_code               activity  \
0                1                   1   TMB-NAC      request_submitted
1                2                   1   TMB-NAC       technical_review
2                3                   1   TMB-NAC        wildlife_review
3                4                   1   TMB-NAC        security_review
4                5                   1   TMB-NAC  authorization_granted

         requesting_organization_name requesting_registration_number  \
0  Horizon Field Research Cooperative                      AVL-01013
1  Horizon Field Research Cooperative                      AVL-01013
2  Horizon Field Research Cooperative                      AVL-01013
3  Horizon Field Research Cooperative                      AVL-01013
4  Horizon Field Research Cooperative                      AVL-01013

             authorizing_agency authorized_person_name  \
0  Tembara Biodiversity Service            Bela Ferran
1  Tembara Biodiversity Service           Kellan Orell
2  Tembara Biodiversity Service           Jalen Quorin
3  Tembara Biodiversity Service            Jalen Zorin
4  Tembara Biodiversity Service              Xara Lask

                                  access_purpose  \
0  acoustic monitoring and equipment maintenance
1  acoustic monitoring and equipment maintenance
2  acoustic monitoring and equipment maintenance
3  acoustic monitoring and equipment maintenance
4  acoustic monitoring and equipment maintenance

                               equipment_category   previous_status  \
0  portable monitoring and cold-storage equipment             draft
1  portable monitoring and cold-storage equipment         submitted
2  portable monitoring and cold-storage equipment  technical_review
3  portable monitoring and cold-storage equipment   wildlife_review
4  portable monitoring and cold-storage equipment   security_review

         new_status confidentiality_class                            outcome  \
0         submitted            restricted                     request logged
1  technical_review            restricted         technical review completed
2   wildlife_review            restricted       wildlife conditions recorded
3   security_review            restricted  site-security conditions recorded
4        authorized            restricted               authorization issued

   event_hour  event_year  event_month  event_day
0           9        2018            1         15
1           9        2018            1         21
2           9        2018            1         26
3           9        2018            1         30
4           9        2018            2          5

In [104]:
df_sac[['registration_type', 'registration_number']] = df_sac['requesting_registration_number'].str.split('-', n=1, expand=True)
df_sac = df_sac.drop('requesting_registration_number', axis=1)

In [102]:
#on peut executer qu'une fois ici aussi
df_sac = pd.get_dummies(df_sac, columns=['confidentiality_class', 'registration_type'], prefix='', prefix_sep='', dtype=int)
display(df_sac.head())

,access_event_id,access_case_number,site_code,activity,requesting_organization_name,requesting_registration_number,authorizing_agency,authorized_person_name,access_purpose,equipment_category,previous_status,new_status,outcome,event_hour,event_year,event_month,event_day,confidential,restricted,standard
0,1,1,TMB-NAC,request_submitted,Horizon Field Research Cooperative,AVL-01013,Tembara Biodiversity Service,Bela Ferran,acoustic monitoring and equipment maintenance,portable monitoring and cold-storage equipment,draft,submitted,request logged,9,2018,1,15,0,1,0
1,2,1,TMB-NAC,technical_review,Horizon Field Research Cooperative,AVL-01013,Tembara Biodiversity Service,Kellan Orell,acoustic monitoring and equipment maintenance,portable monitoring and cold-storage equipment,submitted,technical_review,technical review completed,9,2018,1,21,0,1,0
2,3,1,TMB-NAC,wildlife_review,Horizon Field Research Cooperative,AVL-01013,Tembara Biodiversity Service,Jalen Quorin,acoustic monitoring and equipment maintenance,portable monitoring and cold-storage equipment,technical_review,wildlife_review,wildlife conditions recorded,9,2018,1,26,0,1,0
3,4,1,TMB-NAC,security_review,Horizon Field Research Cooperative,AVL-01013,Tembara Biodiversity Service,Jalen Zorin,acoustic monitoring and equipment maintenance,portable monitoring and cold-storage equipment,wildlife_review,security_review,site-security conditions recorded,9,2018,1,30,0,1,0
4,5,1,TMB-NAC,authorization_granted,Horizon Field Research Cooperative,AVL-01013,Tembara Biodiversity Service,Xara Lask,acoustic monitoring and equipment maintenance,portable monitoring and cold-storage equipment,security_review,authorized,authorization issued,9,2018,2,5,0,1,0

In [69]:
# import seaborn as sns
# import matplotlib.pyplot as plt

# corr = df[["Age", "Taille", "Poids", "IMC"]].corr()

# sns.heatmap(corr, annot=True, cmap="coolwarm")
# plt.show()